<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Badge/BadgeCaptureReward.proto

namespace GPBMetadata\POGOProtos\Data\Badge;

class BadgeCaptureReward
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa5010a2e504f474f50726f746f732f446174612f42616467652f426164" .
            "6765436170747572655265776172642e70726f746f1215504f474f50726f" .
            "746f732e446174612e426164676522540a12426164676543617074757265" .
            "52657761726412210a19636170747572655f7265776172645f6d756c7469" .
            "706c696572180120012802121b0a136176617461725f74656d706c617465" .
            "5f696473180220032809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

