<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Capture/CaptureAward.proto

namespace GPBMetadata\POGOProtos\Data\Capture;

class CaptureAward
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Enums\ActivityType::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af7010a2a504f474f50726f746f732f446174612f436170747572652f43" .
            "61707475726541776172642e70726f746f1217504f474f50726f746f732e" .
            "446174612e436170747572651a23504f474f50726f746f732f456e756d73" .
            "2f4163746976697479547970652e70726f746f2282010a0c436170747572" .
            "65417761726412390a0d61637469766974795f7479706518012003280e32" .
            "1e2e504f474f50726f746f732e456e756d732e4163746976697479547970" .
            "6542021001120e0a0278701802200328054202100112110a0563616e6479" .
            "1803200328054202100112140a0873746172647573741804200328054202" .
            "1001620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

