<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/DownloadSettingsAction.proto

namespace POGOProtos\Settings;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Settings.DownloadSettingsAction</code>
 */
class DownloadSettingsAction extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string hash = 1;</code>
     */
    private $hash = '';

    public function __construct() {
        \GPBMetadata\POGOProtos\Settings\DownloadSettingsAction::initOnce();
        parent::__construct();
    }

    /**
     * <code>string hash = 1;</code>
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * <code>string hash = 1;</code>
     */
    public function setHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->hash = $var;
    }

}

