<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/FortSettings.proto

namespace POGOProtos\Settings;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Settings.FortSettings</code>
 */
class FortSettings extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>double interaction_range_meters = 1;</code>
     */
    private $interaction_range_meters = 0.0;
    /**
     * <code>int32 max_total_deployed_pokemon = 2;</code>
     */
    private $max_total_deployed_pokemon = 0;
    /**
     * <code>int32 max_player_deployed_pokemon = 3;</code>
     */
    private $max_player_deployed_pokemon = 0;
    /**
     * <code>double deploy_stamina_multiplier = 4;</code>
     */
    private $deploy_stamina_multiplier = 0.0;
    /**
     * <code>double deploy_attack_multiplier = 5;</code>
     */
    private $deploy_attack_multiplier = 0.0;
    /**
     * <code>double far_interaction_range_meters = 6;</code>
     */
    private $far_interaction_range_meters = 0.0;

    public function __construct() {
        \GPBMetadata\POGOProtos\Settings\FortSettings::initOnce();
        parent::__construct();
    }

    /**
     * <code>double interaction_range_meters = 1;</code>
     */
    public function getInteractionRangeMeters()
    {
        return $this->interaction_range_meters;
    }

    /**
     * <code>double interaction_range_meters = 1;</code>
     */
    public function setInteractionRangeMeters($var)
    {
        GPBUtil::checkDouble($var);
        $this->interaction_range_meters = $var;
    }

    /**
     * <code>int32 max_total_deployed_pokemon = 2;</code>
     */
    public function getMaxTotalDeployedPokemon()
    {
        return $this->max_total_deployed_pokemon;
    }

    /**
     * <code>int32 max_total_deployed_pokemon = 2;</code>
     */
    public function setMaxTotalDeployedPokemon($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_total_deployed_pokemon = $var;
    }

    /**
     * <code>int32 max_player_deployed_pokemon = 3;</code>
     */
    public function getMaxPlayerDeployedPokemon()
    {
        return $this->max_player_deployed_pokemon;
    }

    /**
     * <code>int32 max_player_deployed_pokemon = 3;</code>
     */
    public function setMaxPlayerDeployedPokemon($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_player_deployed_pokemon = $var;
    }

    /**
     * <code>double deploy_stamina_multiplier = 4;</code>
     */
    public function getDeployStaminaMultiplier()
    {
        return $this->deploy_stamina_multiplier;
    }

    /**
     * <code>double deploy_stamina_multiplier = 4;</code>
     */
    public function setDeployStaminaMultiplier($var)
    {
        GPBUtil::checkDouble($var);
        $this->deploy_stamina_multiplier = $var;
    }

    /**
     * <code>double deploy_attack_multiplier = 5;</code>
     */
    public function getDeployAttackMultiplier()
    {
        return $this->deploy_attack_multiplier;
    }

    /**
     * <code>double deploy_attack_multiplier = 5;</code>
     */
    public function setDeployAttackMultiplier($var)
    {
        GPBUtil::checkDouble($var);
        $this->deploy_attack_multiplier = $var;
    }

    /**
     * <code>double far_interaction_range_meters = 6;</code>
     */
    public function getFarInteractionRangeMeters()
    {
        return $this->far_interaction_range_meters;
    }

    /**
     * <code>double far_interaction_range_meters = 6;</code>
     */
    public function setFarInteractionRangeMeters($var)
    {
        GPBUtil::checkDouble($var);
        $this->far_interaction_range_meters = $var;
    }

}

