<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/GpsSettings.proto

namespace POGOProtos\Settings;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Settings.GpsSettings</code>
 */
class GpsSettings extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>float driving_warning_speed_meters_per_second = 1;</code>
     */
    private $driving_warning_speed_meters_per_second = 0.0;
    /**
     * <code>float driving_warning_cooldown_minutes = 2;</code>
     */
    private $driving_warning_cooldown_minutes = 0.0;
    /**
     * <code>float driving_speed_sample_interval_seconds = 3;</code>
     */
    private $driving_speed_sample_interval_seconds = 0.0;
    /**
     * <code>int32 driving_speed_sample_count = 4;</code>
     */
    private $driving_speed_sample_count = 0;

    public function __construct() {
        \GPBMetadata\POGOProtos\Settings\GpsSettings::initOnce();
        parent::__construct();
    }

    /**
     * <code>float driving_warning_speed_meters_per_second = 1;</code>
     */
    public function getDrivingWarningSpeedMetersPerSecond()
    {
        return $this->driving_warning_speed_meters_per_second;
    }

    /**
     * <code>float driving_warning_speed_meters_per_second = 1;</code>
     */
    public function setDrivingWarningSpeedMetersPerSecond($var)
    {
        GPBUtil::checkFloat($var);
        $this->driving_warning_speed_meters_per_second = $var;
    }

    /**
     * <code>float driving_warning_cooldown_minutes = 2;</code>
     */
    public function getDrivingWarningCooldownMinutes()
    {
        return $this->driving_warning_cooldown_minutes;
    }

    /**
     * <code>float driving_warning_cooldown_minutes = 2;</code>
     */
    public function setDrivingWarningCooldownMinutes($var)
    {
        GPBUtil::checkFloat($var);
        $this->driving_warning_cooldown_minutes = $var;
    }

    /**
     * <code>float driving_speed_sample_interval_seconds = 3;</code>
     */
    public function getDrivingSpeedSampleIntervalSeconds()
    {
        return $this->driving_speed_sample_interval_seconds;
    }

    /**
     * <code>float driving_speed_sample_interval_seconds = 3;</code>
     */
    public function setDrivingSpeedSampleIntervalSeconds($var)
    {
        GPBUtil::checkFloat($var);
        $this->driving_speed_sample_interval_seconds = $var;
    }

    /**
     * <code>int32 driving_speed_sample_count = 4;</code>
     */
    public function getDrivingSpeedSampleCount()
    {
        return $this->driving_speed_sample_count;
    }

    /**
     * <code>int32 driving_speed_sample_count = 4;</code>
     */
    public function setDrivingSpeedSampleCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->driving_speed_sample_count = $var;
    }

}

