<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/LevelSettings.proto

namespace POGOProtos\Settings;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Settings.LevelSettings</code>
 */
class LevelSettings extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>double trainer_cp_modifier = 2;</code>
     */
    private $trainer_cp_modifier = 0.0;
    /**
     * <code>double trainer_difficulty_modifier = 3;</code>
     */
    private $trainer_difficulty_modifier = 0.0;

    public function __construct() {
        \GPBMetadata\POGOProtos\Settings\LevelSettings::initOnce();
        parent::__construct();
    }

    /**
     * <code>double trainer_cp_modifier = 2;</code>
     */
    public function getTrainerCpModifier()
    {
        return $this->trainer_cp_modifier;
    }

    /**
     * <code>double trainer_cp_modifier = 2;</code>
     */
    public function setTrainerCpModifier($var)
    {
        GPBUtil::checkDouble($var);
        $this->trainer_cp_modifier = $var;
    }

    /**
     * <code>double trainer_difficulty_modifier = 3;</code>
     */
    public function getTrainerDifficultyModifier()
    {
        return $this->trainer_difficulty_modifier;
    }

    /**
     * <code>double trainer_difficulty_modifier = 3;</code>
     */
    public function setTrainerDifficultyModifier($var)
    {
        GPBUtil::checkDouble($var);
        $this->trainer_difficulty_modifier = $var;
    }

}

