<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/PokemonDisplay.proto

namespace GPBMetadata\POGOProtos\Data;

class PokemonDisplay
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab3010a24504f474f50726f746f732f446174612f506f6b656d6f6e4469" .
            "73706c61792e70726f746f120f504f474f50726f746f732e446174612272" .
            "0a0e506f6b656d6f6e446973706c617912380a07636f7374756d65180120" .
            "01280e32272e504f474f50726f746f732e446174612e506f6b656d6f6e44" .
            "6973706c61792e436f7374756d6522260a07436f7374756d6512090a0555" .
            "4e534554100012100a0c484f4c494441595f323031361001620670726f74" .
            "6f33"
        ));

        static::$is_initialized = true;
    }
}

