<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Platform/PlatformRequestType.proto

/**
 * Protobuf enum <code>POGOProtos.Networking.Platform.PlatformRequestType</code>
 */
namespace POGOProtos\Networking\Platform;

class PlatformRequestType
{
    /**
     * <code>METHOD_UNSET = 0;</code>
     */
    const METHOD_UNSET = 0;
    /**
     * <code>BUY_ITEM_POKECOINS = 2;</code>
     */
    const BUY_ITEM_POKECOINS = 2;
    /**
     * <code>BUY_ITEM_ANDROID = 3;</code>
     */
    const BUY_ITEM_ANDROID = 3;
    /**
     * <code>BUY_ITEM_IOS = 4;</code>
     */
    const BUY_ITEM_IOS = 4;
    /**
     * <code>GET_STORE_ITEMS = 5;</code>
     */
    const GET_STORE_ITEMS = 5;
    /**
     * <code>SEND_ENCRYPTED_SIGNATURE = 6;</code>
     */
    const SEND_ENCRYPTED_SIGNATURE = 6;
}

