<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/Item/ExperienceBoostAttributes.proto

namespace POGOProtos\Settings\Master\Item;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Settings.Master.Item.ExperienceBoostAttributes</code>
 */
class ExperienceBoostAttributes extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>float xp_multiplier = 1;</code>
     */
    private $xp_multiplier = 0.0;
    /**
     * <code>int32 boost_duration_ms = 2;</code>
     */
    private $boost_duration_ms = 0;

    public function __construct() {
        \GPBMetadata\POGOProtos\Settings\Master\Item\ExperienceBoostAttributes::initOnce();
        parent::__construct();
    }

    /**
     * <code>float xp_multiplier = 1;</code>
     */
    public function getXpMultiplier()
    {
        return $this->xp_multiplier;
    }

    /**
     * <code>float xp_multiplier = 1;</code>
     */
    public function setXpMultiplier($var)
    {
        GPBUtil::checkFloat($var);
        $this->xp_multiplier = $var;
    }

    /**
     * <code>int32 boost_duration_ms = 2;</code>
     */
    public function getBoostDurationMs()
    {
        return $this->boost_duration_ms;
    }

    /**
     * <code>int32 boost_duration_ms = 2;</code>
     */
    public function setBoostDurationMs($var)
    {
        GPBUtil::checkInt32($var);
        $this->boost_duration_ms = $var;
    }

}

