<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/Item/InventoryUpgradeAttributes.proto

namespace POGOProtos\Settings\Master\Item;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Settings.Master.Item.InventoryUpgradeAttributes</code>
 */
class InventoryUpgradeAttributes extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 additional_storage = 1;</code>
     */
    private $additional_storage = 0;
    /**
     * <code>.POGOProtos.Inventory.InventoryUpgradeType upgrade_type = 2;</code>
     */
    private $upgrade_type = 0;

    public function __construct() {
        \GPBMetadata\POGOProtos\Settings\Master\Item\InventoryUpgradeAttributes::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 additional_storage = 1;</code>
     */
    public function getAdditionalStorage()
    {
        return $this->additional_storage;
    }

    /**
     * <code>int32 additional_storage = 1;</code>
     */
    public function setAdditionalStorage($var)
    {
        GPBUtil::checkInt32($var);
        $this->additional_storage = $var;
    }

    /**
     * <code>.POGOProtos.Inventory.InventoryUpgradeType upgrade_type = 2;</code>
     */
    public function getUpgradeType()
    {
        return $this->upgrade_type;
    }

    /**
     * <code>.POGOProtos.Inventory.InventoryUpgradeType upgrade_type = 2;</code>
     */
    public function setUpgradeType($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Inventory\InventoryUpgradeType::class);
        $this->upgrade_type = $var;
    }

}

