<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/Item/PokeballAttributes.proto

namespace POGOProtos\Settings\Master\Item;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Settings.Master.Item.PokeballAttributes</code>
 */
class PokeballAttributes extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.POGOProtos.Enums.ItemEffect item_effect = 1;</code>
     */
    private $item_effect = 0;
    /**
     * <code>float capture_multi = 2;</code>
     */
    private $capture_multi = 0.0;
    /**
     * <code>float capture_multi_effect = 3;</code>
     */
    private $capture_multi_effect = 0.0;
    /**
     * <code>float item_effect_mod = 4;</code>
     */
    private $item_effect_mod = 0.0;

    public function __construct() {
        \GPBMetadata\POGOProtos\Settings\Master\Item\PokeballAttributes::initOnce();
        parent::__construct();
    }

    /**
     * <code>.POGOProtos.Enums.ItemEffect item_effect = 1;</code>
     */
    public function getItemEffect()
    {
        return $this->item_effect;
    }

    /**
     * <code>.POGOProtos.Enums.ItemEffect item_effect = 1;</code>
     */
    public function setItemEffect($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Enums\ItemEffect::class);
        $this->item_effect = $var;
    }

    /**
     * <code>float capture_multi = 2;</code>
     */
    public function getCaptureMulti()
    {
        return $this->capture_multi;
    }

    /**
     * <code>float capture_multi = 2;</code>
     */
    public function setCaptureMulti($var)
    {
        GPBUtil::checkFloat($var);
        $this->capture_multi = $var;
    }

    /**
     * <code>float capture_multi_effect = 3;</code>
     */
    public function getCaptureMultiEffect()
    {
        return $this->capture_multi_effect;
    }

    /**
     * <code>float capture_multi_effect = 3;</code>
     */
    public function setCaptureMultiEffect($var)
    {
        GPBUtil::checkFloat($var);
        $this->capture_multi_effect = $var;
    }

    /**
     * <code>float item_effect_mod = 4;</code>
     */
    public function getItemEffectMod()
    {
        return $this->item_effect_mod;
    }

    /**
     * <code>float item_effect_mod = 4;</code>
     */
    public function setItemEffectMod($var)
    {
        GPBUtil::checkFloat($var);
        $this->item_effect_mod = $var;
    }

}

