<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/EquippedBadgeSettings.proto

namespace POGOProtos\Settings\Master;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Settings.Master.EquippedBadgeSettings</code>
 */
class EquippedBadgeSettings extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int64 equip_badge_cooldown_ms = 1;</code>
     */
    private $equip_badge_cooldown_ms = 0;
    /**
     * <code>repeated float catch_probability_bonus = 2;</code>
     */
    private $catch_probability_bonus;
    /**
     * <code>repeated float flee_probability_bonus = 3;</code>
     */
    private $flee_probability_bonus;

    public function __construct() {
        \GPBMetadata\POGOProtos\Settings\Master\EquippedBadgeSettings::initOnce();
        parent::__construct();
    }

    /**
     * <code>int64 equip_badge_cooldown_ms = 1;</code>
     */
    public function getEquipBadgeCooldownMs()
    {
        return $this->equip_badge_cooldown_ms;
    }

    /**
     * <code>int64 equip_badge_cooldown_ms = 1;</code>
     */
    public function setEquipBadgeCooldownMs($var)
    {
        GPBUtil::checkInt64($var);
        $this->equip_badge_cooldown_ms = $var;
    }

    /**
     * <code>repeated float catch_probability_bonus = 2;</code>
     */
    public function getCatchProbabilityBonus()
    {
        return $this->catch_probability_bonus;
    }

    /**
     * <code>repeated float catch_probability_bonus = 2;</code>
     */
    public function setCatchProbabilityBonus(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->catch_probability_bonus = $var;
    }

    /**
     * <code>repeated float flee_probability_bonus = 3;</code>
     */
    public function getFleeProbabilityBonus()
    {
        return $this->flee_probability_bonus;
    }

    /**
     * <code>repeated float flee_probability_bonus = 3;</code>
     */
    public function setFleeProbabilityBonus(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->flee_probability_bonus = $var;
    }

}

