<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/TypeEffectiveSettings.proto

namespace POGOProtos\Settings\Master;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Settings.Master.TypeEffectiveSettings</code>
 */
class TypeEffectiveSettings extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated float attack_scalar = 1;</code>
     */
    private $attack_scalar;
    /**
     * <code>.POGOProtos.Enums.PokemonType attack_type = 2;</code>
     */
    private $attack_type = 0;

    public function __construct() {
        \GPBMetadata\POGOProtos\Settings\Master\TypeEffectiveSettings::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated float attack_scalar = 1;</code>
     */
    public function getAttackScalar()
    {
        return $this->attack_scalar;
    }

    /**
     * <code>repeated float attack_scalar = 1;</code>
     */
    public function setAttackScalar(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->attack_scalar = $var;
    }

    /**
     * <code>.POGOProtos.Enums.PokemonType attack_type = 2;</code>
     */
    public function getAttackType()
    {
        return $this->attack_type;
    }

    /**
     * <code>.POGOProtos.Enums.PokemonType attack_type = 2;</code>
     */
    public function setAttackType($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Enums\PokemonType::class);
        $this->attack_type = $var;
    }

}

