<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Avatar/AvatarCustomization.proto

namespace GPBMetadata\POGOProtos\Data\Avatar;

class AvatarCustomization
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abd020a30504f474f50726f746f732f446174612f4176617461722f4176" .
            "61746172437573746f6d697a6174696f6e2e70726f746f1216504f474f50" .
            "726f746f732e446174612e41766174617222e8010a134176617461724375" .
            "73746f6d697a6174696f6e121a0a126176617461725f74656d706c617465" .
            "5f696418012001280912410a066c6162656c7318022003280e32312e504f" .
            "474f50726f746f732e446174612e4176617461722e417661746172437573" .
            "746f6d697a6174696f6e2e4c6162656c22720a054c6162656c120f0a0b55" .
            "4e5345545f4c4142454c1000120b0a0744454641554c54100112090a054f" .
            "574e45441002120c0a084645415455524544100312070a034e4557100412" .
            "080a0453414c451005120f0a0b5055524348415341424c451006120e0a0a" .
            "554e4c4f434b41424c451007620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

