<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/Item/PotionAttributes.proto

namespace GPBMetadata\POGOProtos\Settings\Master\Item;

class PotionAttributes
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9e010a36504f474f50726f746f732f53657474696e67732f4d61737465" .
            "722f4974656d2f506f74696f6e417474726962757465732e70726f746f12" .
            "1f504f474f50726f746f732e53657474696e67732e4d61737465722e4974" .
            "656d223b0a10506f74696f6e4174747269627574657312130a0b7374615f" .
            "70657263656e7418012001280212120a0a7374615f616d6f756e74180220" .
            "012805620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

