<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/LevelSettings.proto

namespace GPBMetadata\POGOProtos\Settings;

class LevelSettings
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a99010a27504f474f50726f746f732f53657474696e67732f4c6576656c" .
            "53657474696e67732e70726f746f1213504f474f50726f746f732e536574" .
            "74696e677322510a0d4c6576656c53657474696e6773121b0a1374726169" .
            "6e65725f63705f6d6f64696669657218022001280112230a1b747261696e" .
            "65725f646966666963756c74795f6d6f6469666965721803200128016206" .
            "70726f746f33"
        ));

        static::$is_initialized = true;
    }
}

