<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Envelopes/Signature.proto

namespace POGOProtos\Networking\Envelopes;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Envelopes.Signature</code>
 */
class Signature extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .POGOProtos.Networking.Envelopes.UnknownMessage field1 = 1;</code>
     */
    private $field1;
    /**
     * <pre>
     * in ms
     * </pre>
     *
     * <code>uint64 timestamp_since_start = 2;</code>
     */
    private $timestamp_since_start = 0;
    /**
     * <code>string field3 = 3;</code>
     */
    private $field3 = '';
    /**
     * <code>repeated .POGOProtos.Networking.Envelopes.Signature.LocationFix location_fix = 4;</code>
     */
    private $location_fix;
    /**
     * <code>repeated .POGOProtos.Networking.Envelopes.Signature.AndroidGpsInfo gps_info = 5;</code>
     */
    private $gps_info;
    /**
     * <code>repeated .POGOProtos.Networking.Envelopes.UnknownMessage field6 = 6;</code>
     */
    private $field6;
    /**
     * <code>repeated .POGOProtos.Networking.Envelopes.Signature.SensorInfo sensor_info = 7;</code>
     */
    private $sensor_info;
    /**
     * <code>.POGOProtos.Networking.Envelopes.Signature.DeviceInfo device_info = 8;</code>
     */
    private $device_info = null;
    /**
     * <code>.POGOProtos.Networking.Envelopes.Signature.ActivityStatus activity_status = 9;</code>
     */
    private $activity_status = null;
    /**
     * <code>int32 location_hash1 = 10;</code>
     */
    private $location_hash1 = 0;
    /**
     * <code>bool field11 = 11;</code>
     */
    private $field11 = false;
    /**
     * <code>bool field12 = 12;</code>
     */
    private $field12 = false;
    /**
     * <code>int32 field13 = 13;</code>
     */
    private $field13 = 0;
    /**
     * <code>int32 field14 = 14;</code>
     */
    private $field14 = 0;
    /**
     * <code>string field15 = 15;</code>
     */
    private $field15 = '';
    /**
     * <code>int32 field16 = 16;</code>
     */
    private $field16 = 0;
    /**
     * <code>string field17 = 17;</code>
     */
    private $field17 = '';
    /**
     * <code>string field18 = 18;</code>
     */
    private $field18 = '';
    /**
     * <code>bool field19 = 19;</code>
     */
    private $field19 = false;
    /**
     * <code>int32 location_hash2 = 20;</code>
     */
    private $location_hash2 = 0;
    /**
     * <code>bool field21 = 21;</code>
     */
    private $field21 = false;
    /**
     * <pre>
     * 32 random bytes, unique per session.
     * </pre>
     *
     * <code>bytes session_hash = 22;</code>
     */
    private $session_hash = '';
    /**
     * <pre>
     * epoch timestamp in ms
     * </pre>
     *
     * <code>uint64 timestamp = 23;</code>
     */
    private $timestamp = 0;
    /**
     * <pre>
     * hashes of each request message in a hashArray signed based on the auth_token or auth_info - xxhash64
     * </pre>
     *
     * <code>repeated uint64 request_hash = 24;</code>
     */
    private $request_hash;
    /**
     * <code>int64 unknown25 = 25;</code>
     */
    private $unknown25 = 0;

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Envelopes\Signature::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .POGOProtos.Networking.Envelopes.UnknownMessage field1 = 1;</code>
     */
    public function getField1()
    {
        return $this->field1;
    }

    /**
     * <code>repeated .POGOProtos.Networking.Envelopes.UnknownMessage field1 = 1;</code>
     */
    public function setField1(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \POGOProtos\Networking\Envelopes\UnknownMessage::class);
        $this->field1 = $var;
    }

    /**
     * <pre>
     * in ms
     * </pre>
     *
     * <code>uint64 timestamp_since_start = 2;</code>
     */
    public function getTimestampSinceStart()
    {
        return $this->timestamp_since_start;
    }

    /**
     * <pre>
     * in ms
     * </pre>
     *
     * <code>uint64 timestamp_since_start = 2;</code>
     */
    public function setTimestampSinceStart($var)
    {
        GPBUtil::checkUint64($var);
        $this->timestamp_since_start = $var;
    }

    /**
     * <code>string field3 = 3;</code>
     */
    public function getField3()
    {
        return $this->field3;
    }

    /**
     * <code>string field3 = 3;</code>
     */
    public function setField3($var)
    {
        GPBUtil::checkString($var, True);
        $this->field3 = $var;
    }

    /**
     * <code>repeated .POGOProtos.Networking.Envelopes.Signature.LocationFix location_fix = 4;</code>
     */
    public function getLocationFix()
    {
        return $this->location_fix;
    }

    /**
     * <code>repeated .POGOProtos.Networking.Envelopes.Signature.LocationFix location_fix = 4;</code>
     */
    public function setLocationFix(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \POGOProtos\Networking\Envelopes\Signature_LocationFix::class);
        $this->location_fix = $var;
    }

    /**
     * <code>repeated .POGOProtos.Networking.Envelopes.Signature.AndroidGpsInfo gps_info = 5;</code>
     */
    public function getGpsInfo()
    {
        return $this->gps_info;
    }

    /**
     * <code>repeated .POGOProtos.Networking.Envelopes.Signature.AndroidGpsInfo gps_info = 5;</code>
     */
    public function setGpsInfo(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \POGOProtos\Networking\Envelopes\Signature_AndroidGpsInfo::class);
        $this->gps_info = $var;
    }

    /**
     * <code>repeated .POGOProtos.Networking.Envelopes.UnknownMessage field6 = 6;</code>
     */
    public function getField6()
    {
        return $this->field6;
    }

    /**
     * <code>repeated .POGOProtos.Networking.Envelopes.UnknownMessage field6 = 6;</code>
     */
    public function setField6(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \POGOProtos\Networking\Envelopes\UnknownMessage::class);
        $this->field6 = $var;
    }

    /**
     * <code>repeated .POGOProtos.Networking.Envelopes.Signature.SensorInfo sensor_info = 7;</code>
     */
    public function getSensorInfo()
    {
        return $this->sensor_info;
    }

    /**
     * <code>repeated .POGOProtos.Networking.Envelopes.Signature.SensorInfo sensor_info = 7;</code>
     */
    public function setSensorInfo(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \POGOProtos\Networking\Envelopes\Signature_SensorInfo::class);
        $this->sensor_info = $var;
    }

    /**
     * <code>.POGOProtos.Networking.Envelopes.Signature.DeviceInfo device_info = 8;</code>
     */
    public function getDeviceInfo()
    {
        return $this->device_info;
    }

    /**
     * <code>.POGOProtos.Networking.Envelopes.Signature.DeviceInfo device_info = 8;</code>
     */
    public function setDeviceInfo(&$var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Networking\Envelopes\Signature_DeviceInfo::class);
        $this->device_info = $var;
    }

    /**
     * <code>.POGOProtos.Networking.Envelopes.Signature.ActivityStatus activity_status = 9;</code>
     */
    public function getActivityStatus()
    {
        return $this->activity_status;
    }

    /**
     * <code>.POGOProtos.Networking.Envelopes.Signature.ActivityStatus activity_status = 9;</code>
     */
    public function setActivityStatus(&$var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Networking\Envelopes\Signature_ActivityStatus::class);
        $this->activity_status = $var;
    }

    /**
     * <code>int32 location_hash1 = 10;</code>
     */
    public function getLocationHash1()
    {
        return $this->location_hash1;
    }

    /**
     * <code>int32 location_hash1 = 10;</code>
     */
    public function setLocationHash1($var)
    {
        GPBUtil::checkInt32($var);
        $this->location_hash1 = $var;
    }

    /**
     * <code>bool field11 = 11;</code>
     */
    public function getField11()
    {
        return $this->field11;
    }

    /**
     * <code>bool field11 = 11;</code>
     */
    public function setField11($var)
    {
        GPBUtil::checkBool($var);
        $this->field11 = $var;
    }

    /**
     * <code>bool field12 = 12;</code>
     */
    public function getField12()
    {
        return $this->field12;
    }

    /**
     * <code>bool field12 = 12;</code>
     */
    public function setField12($var)
    {
        GPBUtil::checkBool($var);
        $this->field12 = $var;
    }

    /**
     * <code>int32 field13 = 13;</code>
     */
    public function getField13()
    {
        return $this->field13;
    }

    /**
     * <code>int32 field13 = 13;</code>
     */
    public function setField13($var)
    {
        GPBUtil::checkInt32($var);
        $this->field13 = $var;
    }

    /**
     * <code>int32 field14 = 14;</code>
     */
    public function getField14()
    {
        return $this->field14;
    }

    /**
     * <code>int32 field14 = 14;</code>
     */
    public function setField14($var)
    {
        GPBUtil::checkInt32($var);
        $this->field14 = $var;
    }

    /**
     * <code>string field15 = 15;</code>
     */
    public function getField15()
    {
        return $this->field15;
    }

    /**
     * <code>string field15 = 15;</code>
     */
    public function setField15($var)
    {
        GPBUtil::checkString($var, True);
        $this->field15 = $var;
    }

    /**
     * <code>int32 field16 = 16;</code>
     */
    public function getField16()
    {
        return $this->field16;
    }

    /**
     * <code>int32 field16 = 16;</code>
     */
    public function setField16($var)
    {
        GPBUtil::checkInt32($var);
        $this->field16 = $var;
    }

    /**
     * <code>string field17 = 17;</code>
     */
    public function getField17()
    {
        return $this->field17;
    }

    /**
     * <code>string field17 = 17;</code>
     */
    public function setField17($var)
    {
        GPBUtil::checkString($var, True);
        $this->field17 = $var;
    }

    /**
     * <code>string field18 = 18;</code>
     */
    public function getField18()
    {
        return $this->field18;
    }

    /**
     * <code>string field18 = 18;</code>
     */
    public function setField18($var)
    {
        GPBUtil::checkString($var, True);
        $this->field18 = $var;
    }

    /**
     * <code>bool field19 = 19;</code>
     */
    public function getField19()
    {
        return $this->field19;
    }

    /**
     * <code>bool field19 = 19;</code>
     */
    public function setField19($var)
    {
        GPBUtil::checkBool($var);
        $this->field19 = $var;
    }

    /**
     * <code>int32 location_hash2 = 20;</code>
     */
    public function getLocationHash2()
    {
        return $this->location_hash2;
    }

    /**
     * <code>int32 location_hash2 = 20;</code>
     */
    public function setLocationHash2($var)
    {
        GPBUtil::checkInt32($var);
        $this->location_hash2 = $var;
    }

    /**
     * <code>bool field21 = 21;</code>
     */
    public function getField21()
    {
        return $this->field21;
    }

    /**
     * <code>bool field21 = 21;</code>
     */
    public function setField21($var)
    {
        GPBUtil::checkBool($var);
        $this->field21 = $var;
    }

    /**
     * <pre>
     * 32 random bytes, unique per session.
     * </pre>
     *
     * <code>bytes session_hash = 22;</code>
     */
    public function getSessionHash()
    {
        return $this->session_hash;
    }

    /**
     * <pre>
     * 32 random bytes, unique per session.
     * </pre>
     *
     * <code>bytes session_hash = 22;</code>
     */
    public function setSessionHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->session_hash = $var;
    }

    /**
     * <pre>
     * epoch timestamp in ms
     * </pre>
     *
     * <code>uint64 timestamp = 23;</code>
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * <pre>
     * epoch timestamp in ms
     * </pre>
     *
     * <code>uint64 timestamp = 23;</code>
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->timestamp = $var;
    }

    /**
     * <pre>
     * hashes of each request message in a hashArray signed based on the auth_token or auth_info - xxhash64
     * </pre>
     *
     * <code>repeated uint64 request_hash = 24;</code>
     */
    public function getRequestHash()
    {
        return $this->request_hash;
    }

    /**
     * <pre>
     * hashes of each request message in a hashArray signed based on the auth_token or auth_info - xxhash64
     * </pre>
     *
     * <code>repeated uint64 request_hash = 24;</code>
     */
    public function setRequestHash(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->request_hash = $var;
    }

    /**
     * <code>int64 unknown25 = 25;</code>
     */
    public function getUnknown25()
    {
        return $this->unknown25;
    }

    /**
     * <code>int64 unknown25 = 25;</code>
     */
    public function setUnknown25($var)
    {
        GPBUtil::checkInt64($var);
        $this->unknown25 = $var;
    }

}

