<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Envelopes/Signature.proto

namespace POGOProtos\Networking\Envelopes;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Only used in iOS - Android just sends an empty version
 * </pre>
 *
 * Protobuf type <code>POGOProtos.Networking.Envelopes.Signature.ActivityStatus</code>
 */
class Signature_ActivityStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * all of these had 1 as their value
     * </pre>
     *
     * <code>uint64 start_time_ms = 1;</code>
     */
    private $start_time_ms = 0;
    /**
     * <code>bool unknown_status = 2;</code>
     */
    private $unknown_status = false;
    /**
     * <code>bool walking = 3;</code>
     */
    private $walking = false;
    /**
     * <code>bool running = 4;</code>
     */
    private $running = false;
    /**
     * <code>bool stationary = 5;</code>
     */
    private $stationary = false;
    /**
     * <code>bool automotive = 6;</code>
     */
    private $automotive = false;
    /**
     * <code>bool tilting = 7;</code>
     */
    private $tilting = false;
    /**
     * <code>bool cycling = 8;</code>
     */
    private $cycling = false;
    /**
     * <code>bytes status = 9;</code>
     */
    private $status = '';

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Envelopes\Signature::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * all of these had 1 as their value
     * </pre>
     *
     * <code>uint64 start_time_ms = 1;</code>
     */
    public function getStartTimeMs()
    {
        return $this->start_time_ms;
    }

    /**
     * <pre>
     * all of these had 1 as their value
     * </pre>
     *
     * <code>uint64 start_time_ms = 1;</code>
     */
    public function setStartTimeMs($var)
    {
        GPBUtil::checkUint64($var);
        $this->start_time_ms = $var;
    }

    /**
     * <code>bool unknown_status = 2;</code>
     */
    public function getUnknownStatus()
    {
        return $this->unknown_status;
    }

    /**
     * <code>bool unknown_status = 2;</code>
     */
    public function setUnknownStatus($var)
    {
        GPBUtil::checkBool($var);
        $this->unknown_status = $var;
    }

    /**
     * <code>bool walking = 3;</code>
     */
    public function getWalking()
    {
        return $this->walking;
    }

    /**
     * <code>bool walking = 3;</code>
     */
    public function setWalking($var)
    {
        GPBUtil::checkBool($var);
        $this->walking = $var;
    }

    /**
     * <code>bool running = 4;</code>
     */
    public function getRunning()
    {
        return $this->running;
    }

    /**
     * <code>bool running = 4;</code>
     */
    public function setRunning($var)
    {
        GPBUtil::checkBool($var);
        $this->running = $var;
    }

    /**
     * <code>bool stationary = 5;</code>
     */
    public function getStationary()
    {
        return $this->stationary;
    }

    /**
     * <code>bool stationary = 5;</code>
     */
    public function setStationary($var)
    {
        GPBUtil::checkBool($var);
        $this->stationary = $var;
    }

    /**
     * <code>bool automotive = 6;</code>
     */
    public function getAutomotive()
    {
        return $this->automotive;
    }

    /**
     * <code>bool automotive = 6;</code>
     */
    public function setAutomotive($var)
    {
        GPBUtil::checkBool($var);
        $this->automotive = $var;
    }

    /**
     * <code>bool tilting = 7;</code>
     */
    public function getTilting()
    {
        return $this->tilting;
    }

    /**
     * <code>bool tilting = 7;</code>
     */
    public function setTilting($var)
    {
        GPBUtil::checkBool($var);
        $this->tilting = $var;
    }

    /**
     * <code>bool cycling = 8;</code>
     */
    public function getCycling()
    {
        return $this->cycling;
    }

    /**
     * <code>bool cycling = 8;</code>
     */
    public function setCycling($var)
    {
        GPBUtil::checkBool($var);
        $this->cycling = $var;
    }

    /**
     * <code>bytes status = 9;</code>
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * <code>bytes status = 9;</code>
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, False);
        $this->status = $var;
    }

}

