<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Platform/PlatformRequestType.proto

namespace GPBMetadata\POGOProtos\Networking\Platform;

class PlatformRequestType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aff010a38504f474f50726f746f732f4e6574776f726b696e672f506c61" .
            "74666f726d2f506c6174666f726d52657175657374547970652e70726f74" .
            "6f121e504f474f50726f746f732e4e6574776f726b696e672e506c617466" .
            "6f726d2a9a010a13506c6174666f726d526571756573745479706512100a" .
            "0c4d4554484f445f554e534554100012160a124255595f4954454d5f504f" .
            "4b45434f494e53100212140a104255595f4954454d5f414e44524f494410" .
            "0312100a0c4255595f4954454d5f494f53100412130a0f4745545f53544f" .
            "52455f4954454d531005121c0a1853454e445f454e435259505445445f53" .
            "49474e41545552451006620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

