<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Player/ContactSettings.proto

namespace POGOProtos\Data\Player;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Data.Player.ContactSettings</code>
 */
class ContactSettings extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>bool send_marketing_emails = 1;</code>
     */
    private $send_marketing_emails = false;
    /**
     * <code>bool send_push_notifications = 2;</code>
     */
    private $send_push_notifications = false;

    public function __construct() {
        \GPBMetadata\POGOProtos\Data\Player\ContactSettings::initOnce();
        parent::__construct();
    }

    /**
     * <code>bool send_marketing_emails = 1;</code>
     */
    public function getSendMarketingEmails()
    {
        return $this->send_marketing_emails;
    }

    /**
     * <code>bool send_marketing_emails = 1;</code>
     */
    public function setSendMarketingEmails($var)
    {
        GPBUtil::checkBool($var);
        $this->send_marketing_emails = $var;
    }

    /**
     * <code>bool send_push_notifications = 2;</code>
     */
    public function getSendPushNotifications()
    {
        return $this->send_push_notifications;
    }

    /**
     * <code>bool send_push_notifications = 2;</code>
     */
    public function setSendPushNotifications($var)
    {
        GPBUtil::checkBool($var);
        $this->send_push_notifications = $var;
    }

}

