<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Player/PlayerCurrency.proto

namespace POGOProtos\Data\Player;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Data.Player.PlayerCurrency</code>
 */
class PlayerCurrency extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 gems = 1;</code>
     */
    private $gems = 0;

    public function __construct() {
        \GPBMetadata\POGOProtos\Data\Player\PlayerCurrency::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 gems = 1;</code>
     */
    public function getGems()
    {
        return $this->gems;
    }

    /**
     * <code>int32 gems = 1;</code>
     */
    public function setGems($var)
    {
        GPBUtil::checkInt32($var);
        $this->gems = $var;
    }

}

