<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Player/PlayerAvatarType.proto

/**
 * Protobuf enum <code>POGOProtos.Data.Player.PlayerAvatarType</code>
 */
namespace POGOProtos\Data\Player;

class PlayerAvatarType
{
    /**
     * <code>PLAYER_AVATAR_MALE = 0;</code>
     */
    const PLAYER_AVATAR_MALE = 0;
    /**
     * <code>PLAYER_AVATAR_FEMALE = 1;</code>
     */
    const PLAYER_AVATAR_FEMALE = 1;
}

