<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Player/DailyBonus.proto

namespace GPBMetadata\POGOProtos\Data\Player;

class DailyBonus
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aae010a27504f474f50726f746f732f446174612f506c617965722f4461" .
            "696c79426f6e75732e70726f746f1216504f474f50726f746f732e446174" .
            "612e506c6179657222630a0a4461696c79426f6e757312230a1b6e657874" .
            "5f636f6c6c65637465645f74696d657374616d705f6d7318012001280312" .
            "300a286e6578745f646566656e6465725f626f6e75735f636f6c6c656374" .
            "5f74696d657374616d705f6d73180220012803620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

