<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Player/PlayerAvatarType.proto

namespace GPBMetadata\POGOProtos\Data\Player;

class PlayerAvatarType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a95010a2d504f474f50726f746f732f446174612f506c617965722f506c" .
            "61796572417661746172547970652e70726f746f1216504f474f50726f74" .
            "6f732e446174612e506c617965722a440a10506c61796572417661746172" .
            "5479706512160a12504c415945525f4156415441525f4d414c4510001218" .
            "0a14504c415945525f4156415441525f46454d414c451001620670726f74" .
            "6f33"
        ));

        static::$is_initialized = true;
    }
}

