<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Request.proto

namespace GPBMetadata\POGOProtos\Networking\Requests;

class Request
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Networking\Requests\RequestType::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aef010a2c504f474f50726f746f732f4e6574776f726b696e672f526571" .
            "75657374732f526571756573742e70726f746f121e504f474f50726f746f" .
            "732e4e6574776f726b696e672e52657175657374731a30504f474f50726f" .
            "746f732f4e6574776f726b696e672f52657175657374732f526571756573" .
            "74547970652e70726f746f22650a075265717565737412410a0c72657175" .
            "6573745f7479706518012001280e322b2e504f474f50726f746f732e4e65" .
            "74776f726b696e672e52657175657374732e526571756573745479706512" .
            "170a0f726571756573745f6d65737361676518022001280c620670726f74" .
            "6f33"
        ));

        static::$is_initialized = true;
    }
}

