<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/CatchPokemonResponse.proto

namespace POGOProtos\Networking\Responses;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Responses.CatchPokemonResponse</code>
 */
class CatchPokemonResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.POGOProtos.Networking.Responses.CatchPokemonResponse.CatchStatus status = 1;</code>
     */
    private $status = 0;
    /**
     * <code>double miss_percent = 2;</code>
     */
    private $miss_percent = 0.0;
    /**
     * <code>fixed64 captured_pokemon_id = 3;</code>
     */
    private $captured_pokemon_id = 0;
    /**
     * <code>.POGOProtos.Data.Capture.CaptureAward capture_award = 4;</code>
     */
    private $capture_award = null;
    /**
     * <code>.POGOProtos.Networking.Responses.CatchPokemonResponse.CaptureReason capture_reason = 5;</code>
     */
    private $capture_reason = 0;
    /**
     * <code>int32 display_pokedex_id = 6;</code>
     */
    private $display_pokedex_id = 0;

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Responses\CatchPokemonResponse::initOnce();
        parent::__construct();
    }

    /**
     * <code>.POGOProtos.Networking.Responses.CatchPokemonResponse.CatchStatus status = 1;</code>
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * <code>.POGOProtos.Networking.Responses.CatchPokemonResponse.CatchStatus status = 1;</code>
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Networking\Responses\CatchPokemonResponse_CatchStatus::class);
        $this->status = $var;
    }

    /**
     * <code>double miss_percent = 2;</code>
     */
    public function getMissPercent()
    {
        return $this->miss_percent;
    }

    /**
     * <code>double miss_percent = 2;</code>
     */
    public function setMissPercent($var)
    {
        GPBUtil::checkDouble($var);
        $this->miss_percent = $var;
    }

    /**
     * <code>fixed64 captured_pokemon_id = 3;</code>
     */
    public function getCapturedPokemonId()
    {
        return $this->captured_pokemon_id;
    }

    /**
     * <code>fixed64 captured_pokemon_id = 3;</code>
     */
    public function setCapturedPokemonId($var)
    {
        GPBUtil::checkUint64($var);
        $this->captured_pokemon_id = $var;
    }

    /**
     * <code>.POGOProtos.Data.Capture.CaptureAward capture_award = 4;</code>
     */
    public function getCaptureAward()
    {
        return $this->capture_award;
    }

    /**
     * <code>.POGOProtos.Data.Capture.CaptureAward capture_award = 4;</code>
     */
    public function setCaptureAward(&$var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Data\Capture\CaptureAward::class);
        $this->capture_award = $var;
    }

    /**
     * <code>.POGOProtos.Networking.Responses.CatchPokemonResponse.CaptureReason capture_reason = 5;</code>
     */
    public function getCaptureReason()
    {
        return $this->capture_reason;
    }

    /**
     * <code>.POGOProtos.Networking.Responses.CatchPokemonResponse.CaptureReason capture_reason = 5;</code>
     */
    public function setCaptureReason($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Networking\Responses\CatchPokemonResponse_CaptureReason::class);
        $this->capture_reason = $var;
    }

    /**
     * <code>int32 display_pokedex_id = 6;</code>
     */
    public function getDisplayPokedexId()
    {
        return $this->display_pokedex_id;
    }

    /**
     * <code>int32 display_pokedex_id = 6;</code>
     */
    public function setDisplayPokedexId($var)
    {
        GPBUtil::checkInt32($var);
        $this->display_pokedex_id = $var;
    }

}

