<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/CheckCodenameAvailableResponse.proto

/**
 * Protobuf enum <code>POGOProtos.Networking.Responses.CheckCodenameAvailableResponse.Status</code>
 */
namespace POGOProtos\Networking\Responses;

class CheckCodenameAvailableResponse_Status
{
    /**
     * <code>UNSET = 0;</code>
     */
    const UNSET = 0;
    /**
     * <code>SUCCESS = 1;</code>
     */
    const SUCCESS = 1;
    /**
     * <code>CODENAME_NOT_AVAILABLE = 2;</code>
     */
    const CODENAME_NOT_AVAILABLE = 2;
    /**
     * <code>CODENAME_NOT_VALID = 3;</code>
     */
    const CODENAME_NOT_VALID = 3;
    /**
     * <code>CURRENT_OWNER = 4;</code>
     */
    const CURRENT_OWNER = 4;
    /**
     * <code>CODENAME_CHANGE_NOT_ALLOWED = 5;</code>
     */
    const CODENAME_CHANGE_NOT_ALLOWED = 5;
}

