<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/DownloadItemTemplatesResponse.proto

namespace POGOProtos\Networking\Responses;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Responses.DownloadItemTemplatesResponse</code>
 */
class DownloadItemTemplatesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>bool success = 1;</code>
     */
    private $success = false;
    /**
     * <code>repeated .POGOProtos.Networking.Responses.DownloadItemTemplatesResponse.ItemTemplate item_templates = 2;</code>
     */
    private $item_templates;
    /**
     * <code>uint64 timestamp_ms = 3;</code>
     */
    private $timestamp_ms = 0;

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Responses\DownloadItemTemplatesResponse::initOnce();
        parent::__construct();
    }

    /**
     * <code>bool success = 1;</code>
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * <code>bool success = 1;</code>
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;
    }

    /**
     * <code>repeated .POGOProtos.Networking.Responses.DownloadItemTemplatesResponse.ItemTemplate item_templates = 2;</code>
     */
    public function getItemTemplates()
    {
        return $this->item_templates;
    }

    /**
     * <code>repeated .POGOProtos.Networking.Responses.DownloadItemTemplatesResponse.ItemTemplate item_templates = 2;</code>
     */
    public function setItemTemplates(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \POGOProtos\Networking\Responses\DownloadItemTemplatesResponse_ItemTemplate::class);
        $this->item_templates = $var;
    }

    /**
     * <code>uint64 timestamp_ms = 3;</code>
     */
    public function getTimestampMs()
    {
        return $this->timestamp_ms;
    }

    /**
     * <code>uint64 timestamp_ms = 3;</code>
     */
    public function setTimestampMs($var)
    {
        GPBUtil::checkUint64($var);
        $this->timestamp_ms = $var;
    }

}

