<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/DownloadSettingsResponse.proto

namespace POGOProtos\Networking\Responses;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Responses.DownloadSettingsResponse</code>
 */
class DownloadSettingsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string error = 1;</code>
     */
    private $error = '';
    /**
     * <code>string hash = 2;</code>
     */
    private $hash = '';
    /**
     * <code>.POGOProtos.Settings.GlobalSettings settings = 3;</code>
     */
    private $settings = null;

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Responses\DownloadSettingsResponse::initOnce();
        parent::__construct();
    }

    /**
     * <code>string error = 1;</code>
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * <code>string error = 1;</code>
     */
    public function setError($var)
    {
        GPBUtil::checkString($var, True);
        $this->error = $var;
    }

    /**
     * <code>string hash = 2;</code>
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * <code>string hash = 2;</code>
     */
    public function setHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->hash = $var;
    }

    /**
     * <code>.POGOProtos.Settings.GlobalSettings settings = 3;</code>
     */
    public function getSettings()
    {
        return $this->settings;
    }

    /**
     * <code>.POGOProtos.Settings.GlobalSettings settings = 3;</code>
     */
    public function setSettings(&$var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Settings\GlobalSettings::class);
        $this->settings = $var;
    }

}

