<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/EquipBadgeResponse.proto

namespace POGOProtos\Networking\Responses;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Responses.EquipBadgeResponse</code>
 */
class EquipBadgeResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.POGOProtos.Networking.Responses.EquipBadgeResponse.Result result = 1;</code>
     */
    private $result = 0;
    /**
     * <code>.POGOProtos.Data.Player.EquippedBadge equipped = 2;</code>
     */
    private $equipped = null;

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Responses\EquipBadgeResponse::initOnce();
        parent::__construct();
    }

    /**
     * <code>.POGOProtos.Networking.Responses.EquipBadgeResponse.Result result = 1;</code>
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * <code>.POGOProtos.Networking.Responses.EquipBadgeResponse.Result result = 1;</code>
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Networking\Responses\EquipBadgeResponse_Result::class);
        $this->result = $var;
    }

    /**
     * <code>.POGOProtos.Data.Player.EquippedBadge equipped = 2;</code>
     */
    public function getEquipped()
    {
        return $this->equipped;
    }

    /**
     * <code>.POGOProtos.Data.Player.EquippedBadge equipped = 2;</code>
     */
    public function setEquipped(&$var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Data\Player\EquippedBadge::class);
        $this->equipped = $var;
    }

}

