<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/GetDownloadUrlsResponse.proto

namespace POGOProtos\Networking\Responses;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Responses.GetDownloadUrlsResponse</code>
 */
class GetDownloadUrlsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .POGOProtos.Data.DownloadUrlEntry download_urls = 1;</code>
     */
    private $download_urls;

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Responses\GetDownloadUrlsResponse::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .POGOProtos.Data.DownloadUrlEntry download_urls = 1;</code>
     */
    public function getDownloadUrls()
    {
        return $this->download_urls;
    }

    /**
     * <code>repeated .POGOProtos.Data.DownloadUrlEntry download_urls = 1;</code>
     */
    public function setDownloadUrls(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \POGOProtos\Data\DownloadUrlEntry::class);
        $this->download_urls = $var;
    }

}

