<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/GetGymDetailsResponse.proto

namespace POGOProtos\Networking\Responses;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Responses.GetGymDetailsResponse</code>
 */
class GetGymDetailsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.POGOProtos.Data.Gym.GymState gym_state = 1;</code>
     */
    private $gym_state = null;
    /**
     * <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * <code>repeated string urls = 3;</code>
     */
    private $urls;
    /**
     * <code>.POGOProtos.Networking.Responses.GetGymDetailsResponse.Result result = 4;</code>
     */
    private $result = 0;
    /**
     * <code>string description = 5;</code>
     */
    private $description = '';
    /**
     * <code>repeated string secondary_url = 6;</code>
     */
    private $secondary_url;

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Responses\GetGymDetailsResponse::initOnce();
        parent::__construct();
    }

    /**
     * <code>.POGOProtos.Data.Gym.GymState gym_state = 1;</code>
     */
    public function getGymState()
    {
        return $this->gym_state;
    }

    /**
     * <code>.POGOProtos.Data.Gym.GymState gym_state = 1;</code>
     */
    public function setGymState(&$var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Data\Gym\GymState::class);
        $this->gym_state = $var;
    }

    /**
     * <code>string name = 2;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <code>string name = 2;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <code>repeated string urls = 3;</code>
     */
    public function getUrls()
    {
        return $this->urls;
    }

    /**
     * <code>repeated string urls = 3;</code>
     */
    public function setUrls(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->urls = $var;
    }

    /**
     * <code>.POGOProtos.Networking.Responses.GetGymDetailsResponse.Result result = 4;</code>
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * <code>.POGOProtos.Networking.Responses.GetGymDetailsResponse.Result result = 4;</code>
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Networking\Responses\GetGymDetailsResponse_Result::class);
        $this->result = $var;
    }

    /**
     * <code>string description = 5;</code>
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * <code>string description = 5;</code>
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;
    }

    /**
     * <code>repeated string secondary_url = 6;</code>
     */
    public function getSecondaryUrl()
    {
        return $this->secondary_url;
    }

    /**
     * <code>repeated string secondary_url = 6;</code>
     */
    public function setSecondaryUrl(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->secondary_url = $var;
    }

}

