<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/GetInventoryResponse.proto

namespace POGOProtos\Networking\Responses;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Responses.GetInventoryResponse</code>
 */
class GetInventoryResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>bool success = 1;</code>
     */
    private $success = false;
    /**
     * <code>.POGOProtos.Inventory.InventoryDelta inventory_delta = 2;</code>
     */
    private $inventory_delta = null;

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Responses\GetInventoryResponse::initOnce();
        parent::__construct();
    }

    /**
     * <code>bool success = 1;</code>
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * <code>bool success = 1;</code>
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;
    }

    /**
     * <code>.POGOProtos.Inventory.InventoryDelta inventory_delta = 2;</code>
     */
    public function getInventoryDelta()
    {
        return $this->inventory_delta;
    }

    /**
     * <code>.POGOProtos.Inventory.InventoryDelta inventory_delta = 2;</code>
     */
    public function setInventoryDelta(&$var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Inventory\InventoryDelta::class);
        $this->inventory_delta = $var;
    }

}

