<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/MarkTutorialCompleteResponse.proto

namespace POGOProtos\Networking\Responses;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Responses.MarkTutorialCompleteResponse</code>
 */
class MarkTutorialCompleteResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>bool success = 1;</code>
     */
    private $success = false;
    /**
     * <code>.POGOProtos.Data.PlayerData player_data = 2;</code>
     */
    private $player_data = null;

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Responses\MarkTutorialCompleteResponse::initOnce();
        parent::__construct();
    }

    /**
     * <code>bool success = 1;</code>
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * <code>bool success = 1;</code>
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;
    }

    /**
     * <code>.POGOProtos.Data.PlayerData player_data = 2;</code>
     */
    public function getPlayerData()
    {
        return $this->player_data;
    }

    /**
     * <code>.POGOProtos.Data.PlayerData player_data = 2;</code>
     */
    public function setPlayerData(&$var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Data\PlayerData::class);
        $this->player_data = $var;
    }

}

