<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/PlayerUpdateResponse.proto

namespace POGOProtos\Networking\Responses;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Responses.PlayerUpdateResponse</code>
 */
class PlayerUpdateResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .POGOProtos.Map.Pokemon.WildPokemon wild_pokemons = 1;</code>
     */
    private $wild_pokemons;
    /**
     * <code>repeated .POGOProtos.Map.Fort.FortData forts = 2;</code>
     */
    private $forts;
    /**
     * <code>int32 forts_nearby = 3;</code>
     */
    private $forts_nearby = 0;

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Responses\PlayerUpdateResponse::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .POGOProtos.Map.Pokemon.WildPokemon wild_pokemons = 1;</code>
     */
    public function getWildPokemons()
    {
        return $this->wild_pokemons;
    }

    /**
     * <code>repeated .POGOProtos.Map.Pokemon.WildPokemon wild_pokemons = 1;</code>
     */
    public function setWildPokemons(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \POGOProtos\Map\Pokemon\WildPokemon::class);
        $this->wild_pokemons = $var;
    }

    /**
     * <code>repeated .POGOProtos.Map.Fort.FortData forts = 2;</code>
     */
    public function getForts()
    {
        return $this->forts;
    }

    /**
     * <code>repeated .POGOProtos.Map.Fort.FortData forts = 2;</code>
     */
    public function setForts(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \POGOProtos\Map\Fort\FortData::class);
        $this->forts = $var;
    }

    /**
     * <code>int32 forts_nearby = 3;</code>
     */
    public function getFortsNearby()
    {
        return $this->forts_nearby;
    }

    /**
     * <code>int32 forts_nearby = 3;</code>
     */
    public function setFortsNearby($var)
    {
        GPBUtil::checkInt32($var);
        $this->forts_nearby = $var;
    }

}

