<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/ReleasePokemonResponse.proto

namespace POGOProtos\Networking\Responses;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Responses.ReleasePokemonResponse</code>
 */
class ReleasePokemonResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.POGOProtos.Networking.Responses.ReleasePokemonResponse.Result result = 1;</code>
     */
    private $result = 0;
    /**
     * <code>int32 candy_awarded = 2;</code>
     */
    private $candy_awarded = 0;

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Responses\ReleasePokemonResponse::initOnce();
        parent::__construct();
    }

    /**
     * <code>.POGOProtos.Networking.Responses.ReleasePokemonResponse.Result result = 1;</code>
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * <code>.POGOProtos.Networking.Responses.ReleasePokemonResponse.Result result = 1;</code>
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Networking\Responses\ReleasePokemonResponse_Result::class);
        $this->result = $var;
    }

    /**
     * <code>int32 candy_awarded = 2;</code>
     */
    public function getCandyAwarded()
    {
        return $this->candy_awarded;
    }

    /**
     * <code>int32 candy_awarded = 2;</code>
     */
    public function setCandyAwarded($var)
    {
        GPBUtil::checkInt32($var);
        $this->candy_awarded = $var;
    }

}

