<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/SetPlayerTeamResponse.proto

namespace POGOProtos\Networking\Responses;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Responses.SetPlayerTeamResponse</code>
 */
class SetPlayerTeamResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.POGOProtos.Networking.Responses.SetPlayerTeamResponse.Status status = 1;</code>
     */
    private $status = 0;
    /**
     * <code>.POGOProtos.Data.PlayerData player_data = 2;</code>
     */
    private $player_data = null;

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Responses\SetPlayerTeamResponse::initOnce();
        parent::__construct();
    }

    /**
     * <code>.POGOProtos.Networking.Responses.SetPlayerTeamResponse.Status status = 1;</code>
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * <code>.POGOProtos.Networking.Responses.SetPlayerTeamResponse.Status status = 1;</code>
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Networking\Responses\SetPlayerTeamResponse_Status::class);
        $this->status = $var;
    }

    /**
     * <code>.POGOProtos.Data.PlayerData player_data = 2;</code>
     */
    public function getPlayerData()
    {
        return $this->player_data;
    }

    /**
     * <code>.POGOProtos.Data.PlayerData player_data = 2;</code>
     */
    public function setPlayerData(&$var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Data\PlayerData::class);
        $this->player_data = $var;
    }

}

