<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/UseIncenseResponse.proto

namespace POGOProtos\Networking\Responses;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Responses.UseIncenseResponse</code>
 */
class UseIncenseResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.POGOProtos.Networking.Responses.UseIncenseResponse.Result result = 1;</code>
     */
    private $result = 0;
    /**
     * <code>.POGOProtos.Inventory.AppliedItem applied_incense = 2;</code>
     */
    private $applied_incense = null;

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Responses\UseIncenseResponse::initOnce();
        parent::__construct();
    }

    /**
     * <code>.POGOProtos.Networking.Responses.UseIncenseResponse.Result result = 1;</code>
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * <code>.POGOProtos.Networking.Responses.UseIncenseResponse.Result result = 1;</code>
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Networking\Responses\UseIncenseResponse_Result::class);
        $this->result = $var;
    }

    /**
     * <code>.POGOProtos.Inventory.AppliedItem applied_incense = 2;</code>
     */
    public function getAppliedIncense()
    {
        return $this->applied_incense;
    }

    /**
     * <code>.POGOProtos.Inventory.AppliedItem applied_incense = 2;</code>
     */
    public function setAppliedIncense(&$var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Inventory\AppliedItem::class);
        $this->applied_incense = $var;
    }

}

