<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/UseItemCaptureResponse.proto

namespace POGOProtos\Networking\Responses;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Responses.UseItemCaptureResponse</code>
 */
class UseItemCaptureResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>bool success = 1;</code>
     */
    private $success = false;
    /**
     * <code>double item_capture_mult = 2;</code>
     */
    private $item_capture_mult = 0.0;
    /**
     * <code>double item_flee_mult = 3;</code>
     */
    private $item_flee_mult = 0.0;
    /**
     * <code>bool stop_movement = 4;</code>
     */
    private $stop_movement = false;
    /**
     * <code>bool stop_attack = 5;</code>
     */
    private $stop_attack = false;
    /**
     * <code>bool target_max = 6;</code>
     */
    private $target_max = false;
    /**
     * <code>bool target_slow = 7;</code>
     */
    private $target_slow = false;

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Responses\UseItemCaptureResponse::initOnce();
        parent::__construct();
    }

    /**
     * <code>bool success = 1;</code>
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * <code>bool success = 1;</code>
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;
    }

    /**
     * <code>double item_capture_mult = 2;</code>
     */
    public function getItemCaptureMult()
    {
        return $this->item_capture_mult;
    }

    /**
     * <code>double item_capture_mult = 2;</code>
     */
    public function setItemCaptureMult($var)
    {
        GPBUtil::checkDouble($var);
        $this->item_capture_mult = $var;
    }

    /**
     * <code>double item_flee_mult = 3;</code>
     */
    public function getItemFleeMult()
    {
        return $this->item_flee_mult;
    }

    /**
     * <code>double item_flee_mult = 3;</code>
     */
    public function setItemFleeMult($var)
    {
        GPBUtil::checkDouble($var);
        $this->item_flee_mult = $var;
    }

    /**
     * <code>bool stop_movement = 4;</code>
     */
    public function getStopMovement()
    {
        return $this->stop_movement;
    }

    /**
     * <code>bool stop_movement = 4;</code>
     */
    public function setStopMovement($var)
    {
        GPBUtil::checkBool($var);
        $this->stop_movement = $var;
    }

    /**
     * <code>bool stop_attack = 5;</code>
     */
    public function getStopAttack()
    {
        return $this->stop_attack;
    }

    /**
     * <code>bool stop_attack = 5;</code>
     */
    public function setStopAttack($var)
    {
        GPBUtil::checkBool($var);
        $this->stop_attack = $var;
    }

    /**
     * <code>bool target_max = 6;</code>
     */
    public function getTargetMax()
    {
        return $this->target_max;
    }

    /**
     * <code>bool target_max = 6;</code>
     */
    public function setTargetMax($var)
    {
        GPBUtil::checkBool($var);
        $this->target_max = $var;
    }

    /**
     * <code>bool target_slow = 7;</code>
     */
    public function getTargetSlow()
    {
        return $this->target_slow;
    }

    /**
     * <code>bool target_slow = 7;</code>
     */
    public function setTargetSlow($var)
    {
        GPBUtil::checkBool($var);
        $this->target_slow = $var;
    }

}

