<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/UseItemReviveResponse.proto

namespace POGOProtos\Networking\Responses;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Responses.UseItemReviveResponse</code>
 */
class UseItemReviveResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.POGOProtos.Networking.Responses.UseItemReviveResponse.Result result = 1;</code>
     */
    private $result = 0;
    /**
     * <code>int32 stamina = 2;</code>
     */
    private $stamina = 0;

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Responses\UseItemReviveResponse::initOnce();
        parent::__construct();
    }

    /**
     * <code>.POGOProtos.Networking.Responses.UseItemReviveResponse.Result result = 1;</code>
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * <code>.POGOProtos.Networking.Responses.UseItemReviveResponse.Result result = 1;</code>
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Networking\Responses\UseItemReviveResponse_Result::class);
        $this->result = $var;
    }

    /**
     * <code>int32 stamina = 2;</code>
     */
    public function getStamina()
    {
        return $this->stamina;
    }

    /**
     * <code>int32 stamina = 2;</code>
     */
    public function setStamina($var)
    {
        GPBUtil::checkInt32($var);
        $this->stamina = $var;
    }

}

