<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Platform/Responses/BuyItemPokeCoinsResponse.proto

namespace GPBMetadata\POGOProtos\Networking\Platform\Responses;

class BuyItemPokeCoinsResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab1020a47504f474f50726f746f732f4e6574776f726b696e672f506c61" .
            "74666f726d2f526573706f6e7365732f4275794974656d506f6b65436f69" .
            "6e73526573706f6e73652e70726f746f1228504f474f50726f746f732e4e" .
            "6574776f726b696e672e506c6174666f726d2e526573706f6e73657322b3" .
            "010a184275794974656d506f6b65436f696e73526573706f6e736512590a" .
            "06726573756c7418012001280e32492e504f474f50726f746f732e4e6574" .
            "776f726b696e672e506c6174666f726d2e526573706f6e7365732e427579" .
            "4974656d506f6b65436f696e73526573706f6e73652e537461747573223c" .
            "0a06537461747573120b0a07554e4b4e4f574e1000120b0a075355434345" .
            "5353100112180a144e4f545f454e4f5547485f504f4b45434f494e531003" .
            "620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

