<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/EquippedBadgeSettings.proto

namespace GPBMetadata\POGOProtos\Settings\Master;

class EquippedBadgeSettings
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad7010a36504f474f50726f746f732f53657474696e67732f4d61737465" .
            "722f4571756970706564426164676553657474696e67732e70726f746f12" .
            "1a504f474f50726f746f732e53657474696e67732e4d617374657222790a" .
            "154571756970706564426164676553657474696e6773121f0a1765717569" .
            "705f62616467655f636f6f6c646f776e5f6d73180120012803121f0a1763" .
            "617463685f70726f626162696c6974795f626f6e7573180220032802121e" .
            "0a16666c65655f70726f626162696c6974795f626f6e7573180320032802" .
            "620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

