<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/MoveSettings.proto

namespace GPBMetadata\POGOProtos\Settings\Master;

class MoveSettings
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Enums\PokemonType::initOnce();
        \GPBMetadata\POGOProtos\Enums\PokemonMove::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0acf040a2d504f474f50726f746f732f53657474696e67732f4d61737465" .
            "722f4d6f766553657474696e67732e70726f746f121a504f474f50726f74" .
            "6f732e53657474696e67732e4d61737465721a22504f474f50726f746f73" .
            "2f456e756d732f506f6b656d6f6e547970652e70726f746f1a22504f474f" .
            "50726f746f732f456e756d732f506f6b656d6f6e4d6f76652e70726f746f" .
            "22b1030a0c4d6f766553657474696e677312320a0b6d6f76656d656e745f" .
            "696418012001280e321d2e504f474f50726f746f732e456e756d732e506f" .
            "6b656d6f6e4d6f766512140a0c616e696d6174696f6e5f69641802200128" .
            "0512330a0c706f6b656d6f6e5f7479706518032001280e321d2e504f474f" .
            "50726f746f732e456e756d732e506f6b656d6f6e54797065120d0a05706f" .
            "77657218042001280212170a0f61636375726163795f6368616e63651805" .
            "2001280212170a0f637269746963616c5f6368616e636518062001280212" .
            "130a0b6865616c5f7363616c6172180720012802121b0a137374616d696e" .
            "615f6c6f73735f7363616c617218082001280212190a11747261696e6572" .
            "5f6c6576656c5f6d696e18092001280512190a11747261696e65725f6c65" .
            "76656c5f6d6178180a2001280512100a087666785f6e616d65180b200128" .
            "0912130a0b6475726174696f6e5f6d73180c20012805121e0a1664616d61" .
            "67655f77696e646f775f73746172745f6d73180d20012805121c0a146461" .
            "6d6167655f77696e646f775f656e645f6d73180e2001280512140a0c656e" .
            "657267795f64656c7461180f20012805620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

