<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Platform/Responses/BuyItemAndroidResponse.proto

/**
 * <pre>
 * THESE ARE SOMEWHAT SPECULATED, failed may be 2
 * </pre>
 *
 * Protobuf enum <code>POGOProtos.Networking.Platform.Responses.BuyItemAndroidResponse.Status</code>
 */
namespace POGOProtos\Networking\Platform\Responses;

class BuyItemAndroidResponse_Status
{
    /**
     * <code>UNKNOWN = 0;</code>
     */
    const UNKNOWN = 0;
    /**
     * <code>SUCCESS = 1;</code>
     */
    const SUCCESS = 1;
}

