<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Inventory/Candy.proto

namespace POGOProtos\Inventory;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Inventory.Candy</code>
 */
class Candy extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.POGOProtos.Enums.PokemonFamilyId family_id = 1;</code>
     */
    private $family_id = 0;
    /**
     * <code>int32 candy = 2;</code>
     */
    private $candy = 0;

    public function __construct() {
        \GPBMetadata\POGOProtos\Inventory\Candy::initOnce();
        parent::__construct();
    }

    /**
     * <code>.POGOProtos.Enums.PokemonFamilyId family_id = 1;</code>
     */
    public function getFamilyId()
    {
        return $this->family_id;
    }

    /**
     * <code>.POGOProtos.Enums.PokemonFamilyId family_id = 1;</code>
     */
    public function setFamilyId($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Enums\PokemonFamilyId::class);
        $this->family_id = $var;
    }

    /**
     * <code>int32 candy = 2;</code>
     */
    public function getCandy()
    {
        return $this->candy;
    }

    /**
     * <code>int32 candy = 2;</code>
     */
    public function setCandy($var)
    {
        GPBUtil::checkInt32($var);
        $this->candy = $var;
    }

}

