<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Inventory/EggIncubator.proto

namespace POGOProtos\Inventory;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Inventory.EggIncubator</code>
 */
class EggIncubator extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * <code>.POGOProtos.Inventory.Item.ItemId item_id = 2;</code>
     */
    private $item_id = 0;
    /**
     * <code>.POGOProtos.Inventory.EggIncubatorType incubator_type = 3;</code>
     */
    private $incubator_type = 0;
    /**
     * <code>int32 uses_remaining = 4;</code>
     */
    private $uses_remaining = 0;
    /**
     * <pre>
     * TODO: Check if is PokemonType
     * </pre>
     *
     * <code>uint64 pokemon_id = 5;</code>
     */
    private $pokemon_id = 0;
    /**
     * <code>double start_km_walked = 6;</code>
     */
    private $start_km_walked = 0.0;
    /**
     * <code>double target_km_walked = 7;</code>
     */
    private $target_km_walked = 0.0;

    public function __construct() {
        \GPBMetadata\POGOProtos\Inventory\EggIncubator::initOnce();
        parent::__construct();
    }

    /**
     * <code>string id = 1;</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <code>string id = 1;</code>
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;
    }

    /**
     * <code>.POGOProtos.Inventory.Item.ItemId item_id = 2;</code>
     */
    public function getItemId()
    {
        return $this->item_id;
    }

    /**
     * <code>.POGOProtos.Inventory.Item.ItemId item_id = 2;</code>
     */
    public function setItemId($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Inventory\Item\ItemId::class);
        $this->item_id = $var;
    }

    /**
     * <code>.POGOProtos.Inventory.EggIncubatorType incubator_type = 3;</code>
     */
    public function getIncubatorType()
    {
        return $this->incubator_type;
    }

    /**
     * <code>.POGOProtos.Inventory.EggIncubatorType incubator_type = 3;</code>
     */
    public function setIncubatorType($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Inventory\EggIncubatorType::class);
        $this->incubator_type = $var;
    }

    /**
     * <code>int32 uses_remaining = 4;</code>
     */
    public function getUsesRemaining()
    {
        return $this->uses_remaining;
    }

    /**
     * <code>int32 uses_remaining = 4;</code>
     */
    public function setUsesRemaining($var)
    {
        GPBUtil::checkInt32($var);
        $this->uses_remaining = $var;
    }

    /**
     * <pre>
     * TODO: Check if is PokemonType
     * </pre>
     *
     * <code>uint64 pokemon_id = 5;</code>
     */
    public function getPokemonId()
    {
        return $this->pokemon_id;
    }

    /**
     * <pre>
     * TODO: Check if is PokemonType
     * </pre>
     *
     * <code>uint64 pokemon_id = 5;</code>
     */
    public function setPokemonId($var)
    {
        GPBUtil::checkUint64($var);
        $this->pokemon_id = $var;
    }

    /**
     * <code>double start_km_walked = 6;</code>
     */
    public function getStartKmWalked()
    {
        return $this->start_km_walked;
    }

    /**
     * <code>double start_km_walked = 6;</code>
     */
    public function setStartKmWalked($var)
    {
        GPBUtil::checkDouble($var);
        $this->start_km_walked = $var;
    }

    /**
     * <code>double target_km_walked = 7;</code>
     */
    public function getTargetKmWalked()
    {
        return $this->target_km_walked;
    }

    /**
     * <code>double target_km_walked = 7;</code>
     */
    public function setTargetKmWalked($var)
    {
        GPBUtil::checkDouble($var);
        $this->target_km_walked = $var;
    }

}

