<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Inventory/InventoryDelta.proto

namespace POGOProtos\Inventory;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Inventory.InventoryDelta</code>
 */
class InventoryDelta extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int64 original_timestamp_ms = 1;</code>
     */
    private $original_timestamp_ms = 0;
    /**
     * <code>int64 new_timestamp_ms = 2;</code>
     */
    private $new_timestamp_ms = 0;
    /**
     * <code>repeated .POGOProtos.Inventory.InventoryItem inventory_items = 3;</code>
     */
    private $inventory_items;

    public function __construct() {
        \GPBMetadata\POGOProtos\Inventory\InventoryDelta::initOnce();
        parent::__construct();
    }

    /**
     * <code>int64 original_timestamp_ms = 1;</code>
     */
    public function getOriginalTimestampMs()
    {
        return $this->original_timestamp_ms;
    }

    /**
     * <code>int64 original_timestamp_ms = 1;</code>
     */
    public function setOriginalTimestampMs($var)
    {
        GPBUtil::checkInt64($var);
        $this->original_timestamp_ms = $var;
    }

    /**
     * <code>int64 new_timestamp_ms = 2;</code>
     */
    public function getNewTimestampMs()
    {
        return $this->new_timestamp_ms;
    }

    /**
     * <code>int64 new_timestamp_ms = 2;</code>
     */
    public function setNewTimestampMs($var)
    {
        GPBUtil::checkInt64($var);
        $this->new_timestamp_ms = $var;
    }

    /**
     * <code>repeated .POGOProtos.Inventory.InventoryItem inventory_items = 3;</code>
     */
    public function getInventoryItems()
    {
        return $this->inventory_items;
    }

    /**
     * <code>repeated .POGOProtos.Inventory.InventoryItem inventory_items = 3;</code>
     */
    public function setInventoryItems(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \POGOProtos\Inventory\InventoryItem::class);
        $this->inventory_items = $var;
    }

}

