<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Inventory/InventoryUpgradeType.proto

/**
 * Protobuf enum <code>POGOProtos.Inventory.InventoryUpgradeType</code>
 */
namespace POGOProtos\Inventory;

class InventoryUpgradeType
{
    /**
     * <code>UPGRADE_UNSET = 0;</code>
     */
    const UPGRADE_UNSET = 0;
    /**
     * <code>INCREASE_ITEM_STORAGE = 1;</code>
     */
    const INCREASE_ITEM_STORAGE = 1;
    /**
     * <code>INCREASE_POKEMON_STORAGE = 2;</code>
     */
    const INCREASE_POKEMON_STORAGE = 2;
}

