<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Map/MapObjectsStatus.proto

/**
 * Protobuf enum <code>POGOProtos.Map.MapObjectsStatus</code>
 */
namespace POGOProtos\Map;

class MapObjectsStatus
{
    /**
     * <code>UNSET_STATUS = 0;</code>
     */
    const UNSET_STATUS = 0;
    /**
     * <code>SUCCESS = 1;</code>
     */
    const SUCCESS = 1;
    /**
     * <code>LOCATION_UNSET = 2;</code>
     */
    const LOCATION_UNSET = 2;
}

