<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Map/Fort/FortRenderingType.proto

/**
 * Protobuf enum <code>POGOProtos.Map.Fort.FortRenderingType</code>
 */
namespace POGOProtos\Map\Fort;

class FortRenderingType
{
    /**
     * <code>DEFAULT = 0;</code>
     */
    const DEFAULT = 0;
    /**
     * <code>INTERNAL_TEST = 1;</code>
     */
    const INTERNAL_TEST = 1;
}

