<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Logs/CatchPokemonLogEntry.proto

namespace GPBMetadata\POGOProtos\Data\Logs;

class CatchPokemonLogEntry
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Enums\PokemonId::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a80030a2f504f474f50726f746f732f446174612f4c6f67732f43617463" .
            "68506f6b656d6f6e4c6f67456e7472792e70726f746f1214504f474f5072" .
            "6f746f732e446174612e4c6f67731a20504f474f50726f746f732f456e75" .
            "6d732f506f6b656d6f6e49642e70726f746f228c020a144361746368506f" .
            "6b656d6f6e4c6f67456e74727912410a06726573756c7418012001280e32" .
            "312e504f474f50726f746f732e446174612e4c6f67732e4361746368506f" .
            "6b656d6f6e4c6f67456e7472792e526573756c74122f0a0a706f6b656d6f" .
            "6e5f696418022001280e321b2e504f474f50726f746f732e456e756d732e" .
            "506f6b656d6f6e496412150a0d636f6d6261745f706f696e747318032001" .
            "280512170a0f706f6b656d6f6e5f646174615f696418042001280622500a" .
            "06526573756c7412090a05554e534554100012140a10504f4b454d4f4e5f" .
            "4341505455524544100112100a0c504f4b454d4f4e5f464c454410021213" .
            "0a0f504f4b454d4f4e5f484154434845441003620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

