<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Logs/FortSearchLogEntry.proto

namespace GPBMetadata\POGOProtos\Data\Logs;

class FortSearchLogEntry
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Inventory\Item\ItemData::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac4020a2d504f474f50726f746f732f446174612f4c6f67732f466f7274" .
            "5365617263684c6f67456e7472792e70726f746f1214504f474f50726f74" .
            "6f732e446174612e4c6f67731a28504f474f50726f746f732f496e76656e" .
            "746f72792f4974656d2f4974656d446174612e70726f746f22ca010a1246" .
            "6f72745365617263684c6f67456e747279123f0a06726573756c74180120" .
            "01280e322f2e504f474f50726f746f732e446174612e4c6f67732e466f72" .
            "745365617263684c6f67456e7472792e526573756c74120f0a07666f7274" .
            "5f696418022001280912320a056974656d7318032003280b32232e504f47" .
            "4f50726f746f732e496e76656e746f72792e4974656d2e4974656d446174" .
            "61120c0a046567677318042001280522200a06526573756c7412090a0555" .
            "4e5345541000120b0a07535543434553531001620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

