<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Platform/Requests/SendEncryptedSignatureRequest.proto

namespace POGOProtos\Networking\Platform\Requests;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Platform.Requests.SendEncryptedSignatureRequest</code>
 */
class SendEncryptedSignatureRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>bytes encrypted_signature = 1;</code>
     */
    private $encrypted_signature = '';

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Platform\Requests\SendEncryptedSignatureRequest::initOnce();
        parent::__construct();
    }

    /**
     * <code>bytes encrypted_signature = 1;</code>
     */
    public function getEncryptedSignature()
    {
        return $this->encrypted_signature;
    }

    /**
     * <code>bytes encrypted_signature = 1;</code>
     */
    public function setEncryptedSignature($var)
    {
        GPBUtil::checkString($var, False);
        $this->encrypted_signature = $var;
    }

}

