<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/CollectDailyBonusResponse.proto

namespace GPBMetadata\POGOProtos\Networking\Responses;

class CollectDailyBonusResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a98020a3f504f474f50726f746f732f4e6574776f726b696e672f526573" .
            "706f6e7365732f436f6c6c6563744461696c79426f6e7573526573706f6e" .
            "73652e70726f746f121f504f474f50726f746f732e4e6574776f726b696e" .
            "672e526573706f6e73657322ab010a19436f6c6c6563744461696c79426f" .
            "6e7573526573706f6e736512510a06726573756c7418012001280e32412e" .
            "504f474f50726f746f732e4e6574776f726b696e672e526573706f6e7365" .
            "732e436f6c6c6563744461696c79426f6e7573526573706f6e73652e5265" .
            "73756c74223b0a06526573756c7412090a05554e5345541000120b0a0753" .
            "5543434553531001120b0a074641494c5552451002120c0a08544f4f5f53" .
            "4f4f4e1003620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

