<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/DownloadSettingsResponse.proto

namespace GPBMetadata\POGOProtos\Networking\Responses;

class DownloadSettingsResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Settings\GlobalSettings::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a83020a3e504f474f50726f746f732f4e6574776f726b696e672f526573" .
            "706f6e7365732f446f776e6c6f616453657474696e6773526573706f6e73" .
            "652e70726f746f121f504f474f50726f746f732e4e6574776f726b696e67" .
            "2e526573706f6e7365731a28504f474f50726f746f732f53657474696e67" .
            "732f476c6f62616c53657474696e67732e70726f746f226e0a18446f776e" .
            "6c6f616453657474696e6773526573706f6e7365120d0a056572726f7218" .
            "0120012809120c0a046861736818022001280912350a0873657474696e67" .
            "7318032001280b32232e504f474f50726f746f732e53657474696e67732e" .
            "476c6f62616c53657474696e6773620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

