<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/EvolvePokemonResponse.proto

namespace GPBMetadata\POGOProtos\Networking\Responses;

class EvolvePokemonResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Data\PokemonData::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a85040a3b504f474f50726f746f732f4e6574776f726b696e672f526573" .
            "706f6e7365732f45766f6c7665506f6b656d6f6e526573706f6e73652e70" .
            "726f746f121f504f474f50726f746f732e4e6574776f726b696e672e5265" .
            "73706f6e7365731a21504f474f50726f746f732f446174612f506f6b656d" .
            "6f6e446174612e70726f746f22f9020a1545766f6c7665506f6b656d6f6e" .
            "526573706f6e7365124d0a06726573756c7418012001280e323d2e504f47" .
            "4f50726f746f732e4e6574776f726b696e672e526573706f6e7365732e45" .
            "766f6c7665506f6b656d6f6e526573706f6e73652e526573756c74123a0a" .
            "1465766f6c7665645f706f6b656d6f6e5f6461746118022001280b321c2e" .
            "504f474f50726f746f732e446174612e506f6b656d6f6e44617461121a0a" .
            "12657870657269656e63655f6177617264656418032001280512150a0d63" .
            "616e64795f6177617264656418042001280522a1010a06526573756c7412" .
            "090a05554e5345541000120b0a07535543434553531001121a0a16464149" .
            "4c45445f504f4b454d4f4e5f4d495353494e47100212210a1d4641494c45" .
            "445f494e53554646494349454e545f5245534f5552434553100312200a1c" .
            "4641494c45445f504f4b454d4f4e5f43414e4e4f545f45564f4c56451004" .
            "121e0a1a4641494c45445f504f4b454d4f4e5f49535f4445504c4f594544" .
            "1005620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

