<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/GetGymDetailsResponse.proto

namespace GPBMetadata\POGOProtos\Networking\Responses;

class GetGymDetailsResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Data\Gym\GymState::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa7030a3b504f474f50726f746f732f4e6574776f726b696e672f526573" .
            "706f6e7365732f47657447796d44657461696c73526573706f6e73652e70" .
            "726f746f121f504f474f50726f746f732e4e6574776f726b696e672e5265" .
            "73706f6e7365731a22504f474f50726f746f732f446174612f47796d2f47" .
            "796d53746174652e70726f746f229a020a1547657447796d44657461696c" .
            "73526573706f6e736512300a0967796d5f737461746518012001280b321d" .
            "2e504f474f50726f746f732e446174612e47796d2e47796d537461746512" .
            "0c0a046e616d65180220012809120c0a0475726c73180320032809124d0a" .
            "06726573756c7418042001280e323d2e504f474f50726f746f732e4e6574" .
            "776f726b696e672e526573706f6e7365732e47657447796d44657461696c" .
            "73526573706f6e73652e526573756c7412130a0b6465736372697074696f" .
            "6e18052001280912150a0d7365636f6e646172795f75726c180620032809" .
            "22380a06526573756c7412090a05554e5345541000120b0a075355434345" .
            "5353100112160a124552524f525f4e4f545f494e5f52414e474510026206" .
            "70726f746f33"
        ));

        static::$is_initialized = true;
    }
}

