<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/GetHatchedEggsResponse.proto

namespace GPBMetadata\POGOProtos\Networking\Responses;

class GetHatchedEggsResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8f020a3c504f474f50726f746f732f4e6574776f726b696e672f526573" .
            "706f6e7365732f4765744861746368656445676773526573706f6e73652e" .
            "70726f746f121f504f474f50726f746f732e4e6574776f726b696e672e52" .
            "6573706f6e73657322a5010a164765744861746368656445676773526573" .
            "706f6e7365120f0a077375636365737318012001280812160a0a706f6b65" .
            "6d6f6e5f696418022003280642021001121a0a12657870657269656e6365" .
            "5f6177617264656418032003280512150a0d63616e64795f617761726465" .
            "6418042003280512180a1073746172647573745f61776172646564180520" .
            "03280512150a0d6567675f6b6d5f77616c6b656418062003280262067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

