<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/NicknamePokemonResponse.proto

namespace GPBMetadata\POGOProtos\Networking\Responses;

class NicknamePokemonResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aca020a3d504f474f50726f746f732f4e6574776f726b696e672f526573" .
            "706f6e7365732f4e69636b6e616d65506f6b656d6f6e526573706f6e7365" .
            "2e70726f746f121f504f474f50726f746f732e4e6574776f726b696e672e" .
            "526573706f6e73657322df010a174e69636b6e616d65506f6b656d6f6e52" .
            "6573706f6e7365124f0a06726573756c7418012001280e323f2e504f474f" .
            "50726f746f732e4e6574776f726b696e672e526573706f6e7365732e4e69" .
            "636b6e616d65506f6b656d6f6e526573706f6e73652e526573756c742273" .
            "0a06526573756c7412090a05554e5345541000120b0a0753554343455353" .
            "1001121a0a164552524f525f494e56414c49445f4e49434b4e414d451002" .
            "121b0a174552524f525f504f4b454d4f4e5f4e4f545f464f554e44100312" .
            "180a144552524f525f504f4b454d4f4e5f49535f4547471004620670726f" .
            "746f33"
        ));

        static::$is_initialized = true;
    }
}

