<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/PlayerUpdateResponse.proto

namespace GPBMetadata\POGOProtos\Networking\Responses;

class PlayerUpdateResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Map\Fort\FortData::initOnce();
        \GPBMetadata\POGOProtos\Map\Pokemon\WildPokemon::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0acc020a3a504f474f50726f746f732f4e6574776f726b696e672f526573" .
            "706f6e7365732f506c61796572557064617465526573706f6e73652e7072" .
            "6f746f121f504f474f50726f746f732e4e6574776f726b696e672e526573" .
            "706f6e7365731a22504f474f50726f746f732f4d61702f466f72742f466f" .
            "7274446174612e70726f746f1a28504f474f50726f746f732f4d61702f50" .
            "6f6b656d6f6e2f57696c64506f6b656d6f6e2e70726f746f2296010a1450" .
            "6c61796572557064617465526573706f6e7365123a0a0d77696c645f706f" .
            "6b656d6f6e7318012003280b32232e504f474f50726f746f732e4d61702e" .
            "506f6b656d6f6e2e57696c64506f6b656d6f6e122c0a05666f7274731802" .
            "2003280b321d2e504f474f50726f746f732e4d61702e466f72742e466f72" .
            "744461746112140a0c666f7274735f6e6561726279180320012805620670" .
            "726f746f33"
        ));

        static::$is_initialized = true;
    }
}

