<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/ReleasePokemonResponse.proto

namespace GPBMetadata\POGOProtos\Networking\Responses;

class ReleasePokemonResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae3020a3c504f474f50726f746f732f4e6574776f726b696e672f526573" .
            "706f6e7365732f52656c65617365506f6b656d6f6e526573706f6e73652e" .
            "70726f746f121f504f474f50726f746f732e4e6574776f726b696e672e52" .
            "6573706f6e73657322f9010a1652656c65617365506f6b656d6f6e526573" .
            "706f6e7365124e0a06726573756c7418012001280e323e2e504f474f5072" .
            "6f746f732e4e6574776f726b696e672e526573706f6e7365732e52656c65" .
            "617365506f6b656d6f6e526573706f6e73652e526573756c7412150a0d63" .
            "616e64795f6177617264656418022001280522780a06526573756c741209" .
            "0a05554e5345541000120b0a0753554343455353100112140a10504f4b45" .
            "4d4f4e5f4445504c4f5945441002120a0a064641494c4544100312180a14" .
            "4552524f525f504f4b454d4f4e5f49535f4547471004121a0a164552524f" .
            "525f504f4b454d4f4e5f49535f42554444591005620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

