<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/SetBuddyPokemonResponse.proto

namespace GPBMetadata\POGOProtos\Networking\Responses;

class SetBuddyPokemonResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Data\BuddyPokemon::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa4030a3d504f474f50726f746f732f4e6574776f726b696e672f526573" .
            "706f6e7365732f5365744275646479506f6b656d6f6e526573706f6e7365" .
            "2e70726f746f121f504f474f50726f746f732e4e6574776f726b696e672e" .
            "526573706f6e7365731a22504f474f50726f746f732f446174612f427564" .
            "6479506f6b656d6f6e2e70726f746f2295020a175365744275646479506f" .
            "6b656d6f6e526573706f6e7365124f0a06726573756c7418012001280e32" .
            "3f2e504f474f50726f746f732e4e6574776f726b696e672e526573706f6e" .
            "7365732e5365744275646479506f6b656d6f6e526573706f6e73652e5265" .
            "73756c7412340a0d757064617465645f627564647918022001280b321d2e" .
            "504f474f50726f746f732e446174612e4275646479506f6b656d6f6e2273" .
            "0a06526573756c7412090a05554e4553541000120b0a0753554343455353" .
            "1001121a0a164552524f525f504f4b454d4f4e5f4445504c4f5945441002" .
            "121b0a174552524f525f504f4b454d4f4e5f4e4f545f4f574e4544100312" .
            "180a144552524f525f504f4b454d4f4e5f49535f4547471004620670726f" .
            "746f33"
        ));

        static::$is_initialized = true;
    }
}

