<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/VerifyChallengeResponse.proto

namespace GPBMetadata\POGOProtos\Networking\Responses;

class VerifyChallengeResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a94010a3d504f474f50726f746f732f4e6574776f726b696e672f526573" .
            "706f6e7365732f5665726966794368616c6c656e6765526573706f6e7365" .
            "2e70726f746f121f504f474f50726f746f732e4e6574776f726b696e672e" .
            "526573706f6e736573222a0a175665726966794368616c6c656e67655265" .
            "73706f6e7365120f0a0773756363657373180120012808620670726f746f" .
            "33"
        ));

        static::$is_initialized = true;
    }
}

