<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Badge/BadgeCaptureReward.proto

namespace POGOProtos\Data\Badge;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Data.Badge.BadgeCaptureReward</code>
 */
class BadgeCaptureReward extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>float capture_reward_multiplier = 1;</code>
     */
    private $capture_reward_multiplier = 0.0;
    /**
     * <code>repeated string avatar_template_ids = 2;</code>
     */
    private $avatar_template_ids;

    public function __construct() {
        \GPBMetadata\POGOProtos\Data\Badge\BadgeCaptureReward::initOnce();
        parent::__construct();
    }

    /**
     * <code>float capture_reward_multiplier = 1;</code>
     */
    public function getCaptureRewardMultiplier()
    {
        return $this->capture_reward_multiplier;
    }

    /**
     * <code>float capture_reward_multiplier = 1;</code>
     */
    public function setCaptureRewardMultiplier($var)
    {
        GPBUtil::checkFloat($var);
        $this->capture_reward_multiplier = $var;
    }

    /**
     * <code>repeated string avatar_template_ids = 2;</code>
     */
    public function getAvatarTemplateIds()
    {
        return $this->avatar_template_ids;
    }

    /**
     * <code>repeated string avatar_template_ids = 2;</code>
     */
    public function setAvatarTemplateIds(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->avatar_template_ids = $var;
    }

}

