<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Enums/CameraInterpolation.proto

/**
 * Protobuf enum <code>POGOProtos.Enums.CameraInterpolation</code>
 */
namespace POGOProtos\Enums;

class CameraInterpolation
{
    /**
     * <code>CAM_INTERP_CUT = 0;</code>
     */
    const CAM_INTERP_CUT = 0;
    /**
     * <code>CAM_INTERP_LINEAR = 1;</code>
     */
    const CAM_INTERP_LINEAR = 1;
    /**
     * <code>CAM_INTERP_SMOOTH = 2;</code>
     */
    const CAM_INTERP_SMOOTH = 2;
    /**
     * <code>CAM_INTERP_SMOOTH_ROT_LINEAR_MOVE = 3;</code>
     */
    const CAM_INTERP_SMOOTH_ROT_LINEAR_MOVE = 3;
    /**
     * <code>CAM_INTERP_DEPENDS = 4;</code>
     */
    const CAM_INTERP_DEPENDS = 4;
}

