<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Enums/CameraTarget.proto

/**
 * Protobuf enum <code>POGOProtos.Enums.CameraTarget</code>
 */
namespace POGOProtos\Enums;

class CameraTarget
{
    /**
     * <code>CAM_TARGET_ATTACKER = 0;</code>
     */
    const CAM_TARGET_ATTACKER = 0;
    /**
     * <code>CAM_TARGET_ATTACKER_EDGE = 1;</code>
     */
    const CAM_TARGET_ATTACKER_EDGE = 1;
    /**
     * <code>CAM_TARGET_ATTACKER_GROUND = 2;</code>
     */
    const CAM_TARGET_ATTACKER_GROUND = 2;
    /**
     * <code>CAM_TARGET_DEFENDER = 3;</code>
     */
    const CAM_TARGET_DEFENDER = 3;
    /**
     * <code>CAM_TARGET_DEFENDER_EDGE = 4;</code>
     */
    const CAM_TARGET_DEFENDER_EDGE = 4;
    /**
     * <code>CAM_TARGET_DEFENDER_GROUND = 5;</code>
     */
    const CAM_TARGET_DEFENDER_GROUND = 5;
    /**
     * <code>CAM_TARGET_ATTACKER_DEFENDER = 6;</code>
     */
    const CAM_TARGET_ATTACKER_DEFENDER = 6;
    /**
     * <code>CAM_TARGET_ATTACKER_DEFENDER_EDGE = 7;</code>
     */
    const CAM_TARGET_ATTACKER_DEFENDER_EDGE = 7;
    /**
     * <code>CAM_TARGET_DEFENDER_ATTACKER = 8;</code>
     */
    const CAM_TARGET_DEFENDER_ATTACKER = 8;
    /**
     * <code>CAM_TARGET_DEFENDER_ATTACKER_EDGE = 9;</code>
     */
    const CAM_TARGET_DEFENDER_ATTACKER_EDGE = 9;
    /**
     * <code>CAM_TARGET_ATTACKER_DEFENDER_MIRROR = 11;</code>
     */
    const CAM_TARGET_ATTACKER_DEFENDER_MIRROR = 11;
    /**
     * <code>CAM_TARGET_SHOULDER_ATTACKER_DEFENDER = 12;</code>
     */
    const CAM_TARGET_SHOULDER_ATTACKER_DEFENDER = 12;
    /**
     * <code>CAM_TARGET_SHOULDER_ATTACKER_DEFENDER_MIRROR = 13;</code>
     */
    const CAM_TARGET_SHOULDER_ATTACKER_DEFENDER_MIRROR = 13;
    /**
     * <code>CAM_TARGET_ATTACKER_DEFENDER_WORLD = 14;</code>
     */
    const CAM_TARGET_ATTACKER_DEFENDER_WORLD = 14;
}

