<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Enums/Gender.proto

/**
 * Protobuf enum <code>POGOProtos.Enums.Gender</code>
 */
namespace POGOProtos\Enums;

class Gender
{
    /**
     * <code>MALE = 0;</code>
     */
    const MALE = 0;
    /**
     * <code>FEMALE = 1;</code>
     */
    const FEMALE = 1;
}

