<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Enums/TeamColor.proto

/**
 * Protobuf enum <code>POGOProtos.Enums.TeamColor</code>
 */
namespace POGOProtos\Enums;

class TeamColor
{
    /**
     * <code>NEUTRAL = 0;</code>
     */
    const NEUTRAL = 0;
    /**
     * <code>BLUE = 1;</code>
     */
    const BLUE = 1;
    /**
     * <code>RED = 2;</code>
     */
    const RED = 2;
    /**
     * <code>YELLOW = 3;</code>
     */
    const YELLOW = 3;
}

