<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Enums/TutorialState.proto

/**
 * Protobuf enum <code>POGOProtos.Enums.TutorialState</code>
 */
namespace POGOProtos\Enums;

class TutorialState
{
    /**
     * <code>LEGAL_SCREEN = 0;</code>
     */
    const LEGAL_SCREEN = 0;
    /**
     * <code>AVATAR_SELECTION = 1;</code>
     */
    const AVATAR_SELECTION = 1;
    /**
     * <code>ACCOUNT_CREATION = 2;</code>
     */
    const ACCOUNT_CREATION = 2;
    /**
     * <code>POKEMON_CAPTURE = 3;</code>
     */
    const POKEMON_CAPTURE = 3;
    /**
     * <code>NAME_SELECTION = 4;</code>
     */
    const NAME_SELECTION = 4;
    /**
     * <code>POKEMON_BERRY = 5;</code>
     */
    const POKEMON_BERRY = 5;
    /**
     * <code>USE_ITEM = 6;</code>
     */
    const USE_ITEM = 6;
    /**
     * <code>FIRST_TIME_EXPERIENCE_COMPLETE = 7;</code>
     */
    const FIRST_TIME_EXPERIENCE_COMPLETE = 7;
    /**
     * <code>POKESTOP_TUTORIAL = 8;</code>
     */
    const POKESTOP_TUTORIAL = 8;
    /**
     * <code>GYM_TUTORIAL = 9;</code>
     */
    const GYM_TUTORIAL = 9;
}

