<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Enums/Platform.proto

namespace GPBMetadata\POGOProtos\Enums;

class Platform
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a7e0a1f504f474f50726f746f732f456e756d732f506c6174666f726d2e" .
            "70726f746f1210504f474f50726f746f732e456e756d732a410a08506c61" .
            "74666f726d12090a05554e534554100012070a03494f531001120b0a0741" .
            "4e44524f4944100212070a034f53581003120b0a0757494e444f57531004" .
            "620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

