<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Enums/PokemonType.proto

namespace GPBMetadata\POGOProtos\Enums;

class PokemonType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9b040a22504f474f50726f746f732f456e756d732f506f6b656d6f6e54" .
            "7970652e70726f746f1210504f474f50726f746f732e456e756d732ada03" .
            "0a0b506f6b656d6f6e5479706512150a11504f4b454d4f4e5f545950455f" .
            "4e4f4e45100012170a13504f4b454d4f4e5f545950455f4e4f524d414c10" .
            "0112190a15504f4b454d4f4e5f545950455f4649474854494e4710021217" .
            "0a13504f4b454d4f4e5f545950455f464c59494e47100312170a13504f4b" .
            "454d4f4e5f545950455f504f49534f4e100412170a13504f4b454d4f4e5f" .
            "545950455f47524f554e44100512150a11504f4b454d4f4e5f545950455f" .
            "524f434b100612140a10504f4b454d4f4e5f545950455f42554710071216" .
            "0a12504f4b454d4f4e5f545950455f47484f5354100812160a12504f4b45" .
            "4d4f4e5f545950455f535445454c100912150a11504f4b454d4f4e5f5459" .
            "50455f46495245100a12160a12504f4b454d4f4e5f545950455f57415445" .
            "52100b12160a12504f4b454d4f4e5f545950455f4752415353100c12190a" .
            "15504f4b454d4f4e5f545950455f454c454354524943100d12180a14504f" .
            "4b454d4f4e5f545950455f50535943484943100e12140a10504f4b454d4f" .
            "4e5f545950455f494345100f12170a13504f4b454d4f4e5f545950455f44" .
            "5241474f4e101012150a11504f4b454d4f4e5f545950455f4441524b1011" .
            "12160a12504f4b454d4f4e5f545950455f46414952591012620670726f74" .
            "6f33"
        ));

        static::$is_initialized = true;
    }
}

