<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/EncounterMessage.proto

namespace POGOProtos\Networking\Requests\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Requests.Messages.EncounterMessage</code>
 */
class EncounterMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>fixed64 encounter_id = 1;</code>
     */
    private $encounter_id = 0;
    /**
     * <code>string spawn_point_id = 2;</code>
     */
    private $spawn_point_id = '';
    /**
     * <code>double player_latitude = 3;</code>
     */
    private $player_latitude = 0.0;
    /**
     * <code>double player_longitude = 4;</code>
     */
    private $player_longitude = 0.0;

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Requests\Messages\EncounterMessage::initOnce();
        parent::__construct();
    }

    /**
     * <code>fixed64 encounter_id = 1;</code>
     */
    public function getEncounterId()
    {
        return $this->encounter_id;
    }

    /**
     * <code>fixed64 encounter_id = 1;</code>
     */
    public function setEncounterId($var)
    {
        GPBUtil::checkUint64($var);
        $this->encounter_id = $var;
    }

    /**
     * <code>string spawn_point_id = 2;</code>
     */
    public function getSpawnPointId()
    {
        return $this->spawn_point_id;
    }

    /**
     * <code>string spawn_point_id = 2;</code>
     */
    public function setSpawnPointId($var)
    {
        GPBUtil::checkString($var, True);
        $this->spawn_point_id = $var;
    }

    /**
     * <code>double player_latitude = 3;</code>
     */
    public function getPlayerLatitude()
    {
        return $this->player_latitude;
    }

    /**
     * <code>double player_latitude = 3;</code>
     */
    public function setPlayerLatitude($var)
    {
        GPBUtil::checkDouble($var);
        $this->player_latitude = $var;
    }

    /**
     * <code>double player_longitude = 4;</code>
     */
    public function getPlayerLongitude()
    {
        return $this->player_longitude;
    }

    /**
     * <code>double player_longitude = 4;</code>
     */
    public function setPlayerLongitude($var)
    {
        GPBUtil::checkDouble($var);
        $this->player_longitude = $var;
    }

}

