<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/FortSearchMessage.proto

namespace POGOProtos\Networking\Requests\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Requests.Messages.FortSearchMessage</code>
 */
class FortSearchMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string fort_id = 1;</code>
     */
    private $fort_id = '';
    /**
     * <code>double player_latitude = 2;</code>
     */
    private $player_latitude = 0.0;
    /**
     * <code>double player_longitude = 3;</code>
     */
    private $player_longitude = 0.0;
    /**
     * <code>double fort_latitude = 4;</code>
     */
    private $fort_latitude = 0.0;
    /**
     * <code>double fort_longitude = 5;</code>
     */
    private $fort_longitude = 0.0;

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Requests\Messages\FortSearchMessage::initOnce();
        parent::__construct();
    }

    /**
     * <code>string fort_id = 1;</code>
     */
    public function getFortId()
    {
        return $this->fort_id;
    }

    /**
     * <code>string fort_id = 1;</code>
     */
    public function setFortId($var)
    {
        GPBUtil::checkString($var, True);
        $this->fort_id = $var;
    }

    /**
     * <code>double player_latitude = 2;</code>
     */
    public function getPlayerLatitude()
    {
        return $this->player_latitude;
    }

    /**
     * <code>double player_latitude = 2;</code>
     */
    public function setPlayerLatitude($var)
    {
        GPBUtil::checkDouble($var);
        $this->player_latitude = $var;
    }

    /**
     * <code>double player_longitude = 3;</code>
     */
    public function getPlayerLongitude()
    {
        return $this->player_longitude;
    }

    /**
     * <code>double player_longitude = 3;</code>
     */
    public function setPlayerLongitude($var)
    {
        GPBUtil::checkDouble($var);
        $this->player_longitude = $var;
    }

    /**
     * <code>double fort_latitude = 4;</code>
     */
    public function getFortLatitude()
    {
        return $this->fort_latitude;
    }

    /**
     * <code>double fort_latitude = 4;</code>
     */
    public function setFortLatitude($var)
    {
        GPBUtil::checkDouble($var);
        $this->fort_latitude = $var;
    }

    /**
     * <code>double fort_longitude = 5;</code>
     */
    public function getFortLongitude()
    {
        return $this->fort_longitude;
    }

    /**
     * <code>double fort_longitude = 5;</code>
     */
    public function setFortLongitude($var)
    {
        GPBUtil::checkDouble($var);
        $this->fort_longitude = $var;
    }

}

