<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/GetAssetDigestMessage.proto

namespace POGOProtos\Networking\Requests\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Requests.Messages.GetAssetDigestMessage</code>
 */
class GetAssetDigestMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.POGOProtos.Enums.Platform platform = 1;</code>
     */
    private $platform = 0;
    /**
     * <code>string device_manufacturer = 2;</code>
     */
    private $device_manufacturer = '';
    /**
     * <code>string device_model = 3;</code>
     */
    private $device_model = '';
    /**
     * <code>string locale = 4;</code>
     */
    private $locale = '';
    /**
     * <code>uint32 app_version = 5;</code>
     */
    private $app_version = 0;

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Requests\Messages\GetAssetDigestMessage::initOnce();
        parent::__construct();
    }

    /**
     * <code>.POGOProtos.Enums.Platform platform = 1;</code>
     */
    public function getPlatform()
    {
        return $this->platform;
    }

    /**
     * <code>.POGOProtos.Enums.Platform platform = 1;</code>
     */
    public function setPlatform($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Enums\Platform::class);
        $this->platform = $var;
    }

    /**
     * <code>string device_manufacturer = 2;</code>
     */
    public function getDeviceManufacturer()
    {
        return $this->device_manufacturer;
    }

    /**
     * <code>string device_manufacturer = 2;</code>
     */
    public function setDeviceManufacturer($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_manufacturer = $var;
    }

    /**
     * <code>string device_model = 3;</code>
     */
    public function getDeviceModel()
    {
        return $this->device_model;
    }

    /**
     * <code>string device_model = 3;</code>
     */
    public function setDeviceModel($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_model = $var;
    }

    /**
     * <code>string locale = 4;</code>
     */
    public function getLocale()
    {
        return $this->locale;
    }

    /**
     * <code>string locale = 4;</code>
     */
    public function setLocale($var)
    {
        GPBUtil::checkString($var, True);
        $this->locale = $var;
    }

    /**
     * <code>uint32 app_version = 5;</code>
     */
    public function getAppVersion()
    {
        return $this->app_version;
    }

    /**
     * <code>uint32 app_version = 5;</code>
     */
    public function setAppVersion($var)
    {
        GPBUtil::checkUint32($var);
        $this->app_version = $var;
    }

}

