<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/GetPlayerMessage.proto

namespace POGOProtos\Networking\Requests\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Requests.Messages.GetPlayerMessage</code>
 */
class GetPlayerMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.POGOProtos.Networking.Requests.Messages.GetPlayerMessage.PlayerLocale player_locale = 1;</code>
     */
    private $player_locale = null;

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Requests\Messages\GetPlayerMessage::initOnce();
        parent::__construct();
    }

    /**
     * <code>.POGOProtos.Networking.Requests.Messages.GetPlayerMessage.PlayerLocale player_locale = 1;</code>
     */
    public function getPlayerLocale()
    {
        return $this->player_locale;
    }

    /**
     * <code>.POGOProtos.Networking.Requests.Messages.GetPlayerMessage.PlayerLocale player_locale = 1;</code>
     */
    public function setPlayerLocale(&$var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Networking\Requests\Messages\GetPlayerMessage_PlayerLocale::class);
        $this->player_locale = $var;
    }

}

