<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/IncenseEncounterMessage.proto

namespace POGOProtos\Networking\Requests\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Requests.Messages.IncenseEncounterMessage</code>
 */
class IncenseEncounterMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>uint64 encounter_id = 1;</code>
     */
    private $encounter_id = 0;
    /**
     * <code>string encounter_location = 2;</code>
     */
    private $encounter_location = '';

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Requests\Messages\IncenseEncounterMessage::initOnce();
        parent::__construct();
    }

    /**
     * <code>uint64 encounter_id = 1;</code>
     */
    public function getEncounterId()
    {
        return $this->encounter_id;
    }

    /**
     * <code>uint64 encounter_id = 1;</code>
     */
    public function setEncounterId($var)
    {
        GPBUtil::checkUint64($var);
        $this->encounter_id = $var;
    }

    /**
     * <code>string encounter_location = 2;</code>
     */
    public function getEncounterLocation()
    {
        return $this->encounter_location;
    }

    /**
     * <code>string encounter_location = 2;</code>
     */
    public function setEncounterLocation($var)
    {
        GPBUtil::checkString($var, True);
        $this->encounter_location = $var;
    }

}

