<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/SetAvatarMessage.proto

namespace POGOProtos\Networking\Requests\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Requests.Messages.SetAvatarMessage</code>
 */
class SetAvatarMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.POGOProtos.Data.Player.PlayerAvatar player_avatar = 2;</code>
     */
    private $player_avatar = null;

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Requests\Messages\SetAvatarMessage::initOnce();
        parent::__construct();
    }

    /**
     * <code>.POGOProtos.Data.Player.PlayerAvatar player_avatar = 2;</code>
     */
    public function getPlayerAvatar()
    {
        return $this->player_avatar;
    }

    /**
     * <code>.POGOProtos.Data.Player.PlayerAvatar player_avatar = 2;</code>
     */
    public function setPlayerAvatar(&$var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Data\Player\PlayerAvatar::class);
        $this->player_avatar = $var;
    }

}

