<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/UseItemGymMessage.proto

namespace POGOProtos\Networking\Requests\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Requests.Messages.UseItemGymMessage</code>
 */
class UseItemGymMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.POGOProtos.Inventory.Item.ItemId item_id = 1;</code>
     */
    private $item_id = 0;
    /**
     * <code>string gym_id = 2;</code>
     */
    private $gym_id = '';
    /**
     * <code>double player_latitude = 3;</code>
     */
    private $player_latitude = 0.0;
    /**
     * <code>double player_longitude = 4;</code>
     */
    private $player_longitude = 0.0;

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Requests\Messages\UseItemGymMessage::initOnce();
        parent::__construct();
    }

    /**
     * <code>.POGOProtos.Inventory.Item.ItemId item_id = 1;</code>
     */
    public function getItemId()
    {
        return $this->item_id;
    }

    /**
     * <code>.POGOProtos.Inventory.Item.ItemId item_id = 1;</code>
     */
    public function setItemId($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Inventory\Item\ItemId::class);
        $this->item_id = $var;
    }

    /**
     * <code>string gym_id = 2;</code>
     */
    public function getGymId()
    {
        return $this->gym_id;
    }

    /**
     * <code>string gym_id = 2;</code>
     */
    public function setGymId($var)
    {
        GPBUtil::checkString($var, True);
        $this->gym_id = $var;
    }

    /**
     * <code>double player_latitude = 3;</code>
     */
    public function getPlayerLatitude()
    {
        return $this->player_latitude;
    }

    /**
     * <code>double player_latitude = 3;</code>
     */
    public function setPlayerLatitude($var)
    {
        GPBUtil::checkDouble($var);
        $this->player_latitude = $var;
    }

    /**
     * <code>double player_longitude = 4;</code>
     */
    public function getPlayerLongitude()
    {
        return $this->player_longitude;
    }

    /**
     * <code>double player_longitude = 4;</code>
     */
    public function setPlayerLongitude($var)
    {
        GPBUtil::checkDouble($var);
        $this->player_longitude = $var;
    }

}

