<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/UseItemCaptureMessage.proto

namespace POGOProtos\Networking\Requests\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Requests.Messages.UseItemCaptureMessage</code>
 */
class UseItemCaptureMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.POGOProtos.Inventory.Item.ItemId item_id = 1;</code>
     */
    private $item_id = 0;
    /**
     * <code>fixed64 encounter_id = 2;</code>
     */
    private $encounter_id = 0;
    /**
     * <code>string spawn_point_id = 3;</code>
     */
    private $spawn_point_id = '';

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Requests\Messages\UseItemCaptureMessage::initOnce();
        parent::__construct();
    }

    /**
     * <code>.POGOProtos.Inventory.Item.ItemId item_id = 1;</code>
     */
    public function getItemId()
    {
        return $this->item_id;
    }

    /**
     * <code>.POGOProtos.Inventory.Item.ItemId item_id = 1;</code>
     */
    public function setItemId($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Inventory\Item\ItemId::class);
        $this->item_id = $var;
    }

    /**
     * <code>fixed64 encounter_id = 2;</code>
     */
    public function getEncounterId()
    {
        return $this->encounter_id;
    }

    /**
     * <code>fixed64 encounter_id = 2;</code>
     */
    public function setEncounterId($var)
    {
        GPBUtil::checkUint64($var);
        $this->encounter_id = $var;
    }

    /**
     * <code>string spawn_point_id = 3;</code>
     */
    public function getSpawnPointId()
    {
        return $this->spawn_point_id;
    }

    /**
     * <code>string spawn_point_id = 3;</code>
     */
    public function setSpawnPointId($var)
    {
        GPBUtil::checkString($var, True);
        $this->spawn_point_id = $var;
    }

}

