<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Avatar/AvatarCustomization.proto

namespace POGOProtos\Data\Avatar;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Data.Avatar.AvatarCustomization</code>
 */
class AvatarCustomization extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string avatar_template_id = 1;</code>
     */
    private $avatar_template_id = '';
    /**
     * <code>repeated .POGOProtos.Data.Avatar.AvatarCustomization.Label labels = 2;</code>
     */
    private $labels;

    public function __construct() {
        \GPBMetadata\POGOProtos\Data\Avatar\AvatarCustomization::initOnce();
        parent::__construct();
    }

    /**
     * <code>string avatar_template_id = 1;</code>
     */
    public function getAvatarTemplateId()
    {
        return $this->avatar_template_id;
    }

    /**
     * <code>string avatar_template_id = 1;</code>
     */
    public function setAvatarTemplateId($var)
    {
        GPBUtil::checkString($var, True);
        $this->avatar_template_id = $var;
    }

    /**
     * <code>repeated .POGOProtos.Data.Avatar.AvatarCustomization.Label labels = 2;</code>
     */
    public function getLabels()
    {
        return $this->labels;
    }

    /**
     * <code>repeated .POGOProtos.Data.Avatar.AvatarCustomization.Label labels = 2;</code>
     */
    public function setLabels(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, POGOProtos\Data\Avatar\AvatarCustomization_Label::class);
        $this->labels = $var;
    }

}

