<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Map/Pokemon/WildPokemon.proto

namespace POGOProtos\Map\Pokemon;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Map.Pokemon.WildPokemon</code>
 */
class WildPokemon extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>fixed64 encounter_id = 1;</code>
     */
    private $encounter_id = 0;
    /**
     * <code>int64 last_modified_timestamp_ms = 2;</code>
     */
    private $last_modified_timestamp_ms = 0;
    /**
     * <code>double latitude = 3;</code>
     */
    private $latitude = 0.0;
    /**
     * <code>double longitude = 4;</code>
     */
    private $longitude = 0.0;
    /**
     * <code>string spawn_point_id = 5;</code>
     */
    private $spawn_point_id = '';
    /**
     * <code>.POGOProtos.Data.PokemonData pokemon_data = 7;</code>
     */
    private $pokemon_data = null;
    /**
     * <code>int32 time_till_hidden_ms = 11;</code>
     */
    private $time_till_hidden_ms = 0;

    public function __construct() {
        \GPBMetadata\POGOProtos\Map\Pokemon\WildPokemon::initOnce();
        parent::__construct();
    }

    /**
     * <code>fixed64 encounter_id = 1;</code>
     */
    public function getEncounterId()
    {
        return $this->encounter_id;
    }

    /**
     * <code>fixed64 encounter_id = 1;</code>
     */
    public function setEncounterId($var)
    {
        GPBUtil::checkUint64($var);
        $this->encounter_id = $var;
    }

    /**
     * <code>int64 last_modified_timestamp_ms = 2;</code>
     */
    public function getLastModifiedTimestampMs()
    {
        return $this->last_modified_timestamp_ms;
    }

    /**
     * <code>int64 last_modified_timestamp_ms = 2;</code>
     */
    public function setLastModifiedTimestampMs($var)
    {
        GPBUtil::checkInt64($var);
        $this->last_modified_timestamp_ms = $var;
    }

    /**
     * <code>double latitude = 3;</code>
     */
    public function getLatitude()
    {
        return $this->latitude;
    }

    /**
     * <code>double latitude = 3;</code>
     */
    public function setLatitude($var)
    {
        GPBUtil::checkDouble($var);
        $this->latitude = $var;
    }

    /**
     * <code>double longitude = 4;</code>
     */
    public function getLongitude()
    {
        return $this->longitude;
    }

    /**
     * <code>double longitude = 4;</code>
     */
    public function setLongitude($var)
    {
        GPBUtil::checkDouble($var);
        $this->longitude = $var;
    }

    /**
     * <code>string spawn_point_id = 5;</code>
     */
    public function getSpawnPointId()
    {
        return $this->spawn_point_id;
    }

    /**
     * <code>string spawn_point_id = 5;</code>
     */
    public function setSpawnPointId($var)
    {
        GPBUtil::checkString($var, True);
        $this->spawn_point_id = $var;
    }

    /**
     * <code>.POGOProtos.Data.PokemonData pokemon_data = 7;</code>
     */
    public function getPokemonData()
    {
        return $this->pokemon_data;
    }

    /**
     * <code>.POGOProtos.Data.PokemonData pokemon_data = 7;</code>
     */
    public function setPokemonData(&$var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Data\PokemonData::class);
        $this->pokemon_data = $var;
    }

    /**
     * <code>int32 time_till_hidden_ms = 11;</code>
     */
    public function getTimeTillHiddenMs()
    {
        return $this->time_till_hidden_ms;
    }

    /**
     * <code>int32 time_till_hidden_ms = 11;</code>
     */
    public function setTimeTillHiddenMs($var)
    {
        GPBUtil::checkInt32($var);
        $this->time_till_hidden_ms = $var;
    }

}

