<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Map/Pokemon/WildPokemon.proto

namespace GPBMetadata\POGOProtos\Map\Pokemon;

class WildPokemon
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Data\PokemonData::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac5020a28504f474f50726f746f732f4d61702f506f6b656d6f6e2f5769" .
            "6c64506f6b656d6f6e2e70726f746f1216504f474f50726f746f732e4d61" .
            "702e506f6b656d6f6e1a21504f474f50726f746f732f446174612f506f6b" .
            "656d6f6e446174612e70726f746f22d5010a0b57696c64506f6b656d6f6e" .
            "12140a0c656e636f756e7465725f696418012001280612220a1a6c617374" .
            "5f6d6f6469666965645f74696d657374616d705f6d731802200128031210" .
            "0a086c6174697475646518032001280112110a096c6f6e67697475646518" .
            "042001280112160a0e737061776e5f706f696e745f696418052001280912" .
            "320a0c706f6b656d6f6e5f6461746118072001280b321c2e504f474f5072" .
            "6f746f732e446174612e506f6b656d6f6e44617461121b0a1374696d655f" .
            "74696c6c5f68696464656e5f6d73180b20012805620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

