<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Inventory/Item/ItemAward.proto

namespace POGOProtos\Inventory\Item;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Inventory.Item.ItemAward</code>
 */
class ItemAward extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.POGOProtos.Inventory.Item.ItemId item_id = 1;</code>
     */
    private $item_id = 0;
    /**
     * <code>int32 item_count = 2;</code>
     */
    private $item_count = 0;
    /**
     * <code>int32 bonus_count = 3;</code>
     */
    private $bonus_count = 0;

    public function __construct() {
        \GPBMetadata\POGOProtos\Inventory\Item\ItemAward::initOnce();
        parent::__construct();
    }

    /**
     * <code>.POGOProtos.Inventory.Item.ItemId item_id = 1;</code>
     */
    public function getItemId()
    {
        return $this->item_id;
    }

    /**
     * <code>.POGOProtos.Inventory.Item.ItemId item_id = 1;</code>
     */
    public function setItemId($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Inventory\Item\ItemId::class);
        $this->item_id = $var;
    }

    /**
     * <code>int32 item_count = 2;</code>
     */
    public function getItemCount()
    {
        return $this->item_count;
    }

    /**
     * <code>int32 item_count = 2;</code>
     */
    public function setItemCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->item_count = $var;
    }

    /**
     * <code>int32 bonus_count = 3;</code>
     */
    public function getBonusCount()
    {
        return $this->bonus_count;
    }

    /**
     * <code>int32 bonus_count = 3;</code>
     */
    public function setBonusCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->bonus_count = $var;
    }

}

