<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/EncounterTutorialCompleteMessage.proto

namespace GPBMetadata\POGOProtos\Networking\Requests\Messages;

class EncounterTutorialCompleteMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Enums\PokemonId::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af8010a4e504f474f50726f746f732f4e6574776f726b696e672f526571" .
            "75657374732f4d657373616765732f456e636f756e7465725475746f7269" .
            "616c436f6d706c6574654d6573736167652e70726f746f1227504f474f50" .
            "726f746f732e4e6574776f726b696e672e52657175657374732e4d657373" .
            "616765731a20504f474f50726f746f732f456e756d732f506f6b656d6f6e" .
            "49642e70726f746f22530a20456e636f756e7465725475746f7269616c43" .
            "6f6d706c6574654d657373616765122f0a0a706f6b656d6f6e5f69641801" .
            "2001280e321b2e504f474f50726f746f732e456e756d732e506f6b656d6f" .
            "6e4964620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

