<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/FortDeployPokemonMessage.proto

namespace GPBMetadata\POGOProtos\Networking\Requests\Messages;

class FortDeployPokemonMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aed010a46504f474f50726f746f732f4e6574776f726b696e672f526571" .
            "75657374732f4d657373616765732f466f72744465706c6f79506f6b656d" .
            "6f6e4d6573736167652e70726f746f1227504f474f50726f746f732e4e65" .
            "74776f726b696e672e52657175657374732e4d6573736167657322720a18" .
            "466f72744465706c6f79506f6b656d6f6e4d657373616765120f0a07666f" .
            "72745f696418012001280912120a0a706f6b656d6f6e5f69641802200128" .
            "0612170a0f706c617965725f6c6174697475646518032001280112180a10" .
            "706c617965725f6c6f6e676974756465180420012801620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

