<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/IncenseEncounterMessage.proto

namespace GPBMetadata\POGOProtos\Networking\Requests\Messages;

class IncenseEncounterMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac5010a45504f474f50726f746f732f4e6574776f726b696e672f526571" .
            "75657374732f4d657373616765732f496e63656e7365456e636f756e7465" .
            "724d6573736167652e70726f746f1227504f474f50726f746f732e4e6574" .
            "776f726b696e672e52657175657374732e4d65737361676573224b0a1749" .
            "6e63656e7365456e636f756e7465724d65737361676512140a0c656e636f" .
            "756e7465725f6964180120012804121a0a12656e636f756e7465725f6c6f" .
            "636174696f6e180220012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

