<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/SetBuddyPokemon.proto

namespace GPBMetadata\POGOProtos\Networking\Requests\Messages;

class SetBuddyPokemon
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9e010a3d504f474f50726f746f732f4e6574776f726b696e672f526571" .
            "75657374732f4d657373616765732f5365744275646479506f6b656d6f6e" .
            "2e70726f746f1227504f474f50726f746f732e4e6574776f726b696e672e" .
            "52657175657374732e4d65737361676573222c0a16536574427564647950" .
            "6f6b656d6f6e4d65737361676512120a0a706f6b656d6f6e5f6964180120" .
            "012806620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

