<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/StartGymBattleMessage.proto

namespace GPBMetadata\POGOProtos\Networking\Requests\Messages;

class StartGymBattleMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a90020a43504f474f50726f746f732f4e6574776f726b696e672f526571" .
            "75657374732f4d657373616765732f537461727447796d426174746c654d" .
            "6573736167652e70726f746f1227504f474f50726f746f732e4e6574776f" .
            "726b696e672e52657175657374732e4d657373616765732297010a155374" .
            "61727447796d426174746c654d657373616765120e0a0667796d5f696418" .
            "0120012809121d0a1561747461636b696e675f706f6b656d6f6e5f696473" .
            "180220032806121c0a14646566656e64696e675f706f6b656d6f6e5f6964" .
            "18032001280612170a0f706c617965725f6c617469747564651804200128" .
            "0112180a10706c617965725f6c6f6e676974756465180520012801620670" .
            "726f746f33"
        ));

        static::$is_initialized = true;
    }
}

