<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/UseItemGymMessage.proto

namespace GPBMetadata\POGOProtos\Networking\Requests\Messages;

class UseItemGymMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Inventory\Item\ItemId::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa7020a3f504f474f50726f746f732f4e6574776f726b696e672f526571" .
            "75657374732f4d657373616765732f5573654974656d47796d4d65737361" .
            "67652e70726f746f1227504f474f50726f746f732e4e6574776f726b696e" .
            "672e52657175657374732e4d657373616765731a26504f474f50726f746f" .
            "732f496e76656e746f72792f4974656d2f4974656d49642e70726f746f22" .
            "8a010a115573654974656d47796d4d65737361676512320a076974656d5f" .
            "696418012001280e32212e504f474f50726f746f732e496e76656e746f72" .
            "792e4974656d2e4974656d4964120e0a0667796d5f696418022001280912" .
            "170a0f706c617965725f6c6174697475646518032001280112180a10706c" .
            "617965725f6c6f6e676974756465180420012801620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

