<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/UseItemPotionMessage.proto

namespace GPBMetadata\POGOProtos\Networking\Requests\Messages;

class UseItemPotionMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Inventory\Item\ItemId::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0afd010a42504f474f50726f746f732f4e6574776f726b696e672f526571" .
            "75657374732f4d657373616765732f5573654974656d506f74696f6e4d65" .
            "73736167652e70726f746f1227504f474f50726f746f732e4e6574776f72" .
            "6b696e672e52657175657374732e4d657373616765731a26504f474f5072" .
            "6f746f732f496e76656e746f72792f4974656d2f4974656d49642e70726f" .
            "746f225e0a145573654974656d506f74696f6e4d65737361676512320a07" .
            "6974656d5f696418012001280e32212e504f474f50726f746f732e496e76" .
            "656e746f72792e4974656d2e4974656d496412120a0a706f6b656d6f6e5f" .
            "6964180220012806620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

