<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Map/SpawnPoint.proto

namespace GPBMetadata\POGOProtos\Map;

class SpawnPoint
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a6c0a1f504f474f50726f746f732f4d61702f537061776e506f696e742e" .
            "70726f746f120e504f474f50726f746f732e4d617022310a0a537061776e" .
            "506f696e7412100a086c6174697475646518022001280112110a096c6f6e" .
            "676974756465180320012801620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

