<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/DownloadUrlEntry.proto

namespace POGOProtos\Data;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Data.DownloadUrlEntry</code>
 */
class DownloadUrlEntry extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string asset_id = 1;</code>
     */
    private $asset_id = '';
    /**
     * <code>string url = 2;</code>
     */
    private $url = '';
    /**
     * <code>int32 size = 3;</code>
     */
    private $size = 0;
    /**
     * <code>fixed32 checksum = 4;</code>
     */
    private $checksum = 0;

    public function __construct() {
        \GPBMetadata\POGOProtos\Data\DownloadUrlEntry::initOnce();
        parent::__construct();
    }

    /**
     * <code>string asset_id = 1;</code>
     */
    public function getAssetId()
    {
        return $this->asset_id;
    }

    /**
     * <code>string asset_id = 1;</code>
     */
    public function setAssetId($var)
    {
        GPBUtil::checkString($var, True);
        $this->asset_id = $var;
    }

    /**
     * <code>string url = 2;</code>
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * <code>string url = 2;</code>
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;
    }

    /**
     * <code>int32 size = 3;</code>
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * <code>int32 size = 3;</code>
     */
    public function setSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->size = $var;
    }

    /**
     * <code>fixed32 checksum = 4;</code>
     */
    public function getChecksum()
    {
        return $this->checksum;
    }

    /**
     * <code>fixed32 checksum = 4;</code>
     */
    public function setChecksum($var)
    {
        GPBUtil::checkUint32($var);
        $this->checksum = $var;
    }

}

