<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/PlayerData.proto

namespace POGOProtos\Data;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Data.PlayerData</code>
 */
class PlayerData extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int64 creation_timestamp_ms = 1;</code>
     */
    private $creation_timestamp_ms = 0;
    /**
     * <code>string username = 2;</code>
     */
    private $username = '';
    /**
     * <code>.POGOProtos.Enums.TeamColor team = 5;</code>
     */
    private $team = 0;
    /**
     * <code>repeated .POGOProtos.Enums.TutorialState tutorial_state = 7 [packed = true];</code>
     */
    private $tutorial_state;
    /**
     * <code>.POGOProtos.Data.Player.PlayerAvatar avatar = 8;</code>
     */
    private $avatar = null;
    /**
     * <code>int32 max_pokemon_storage = 9;</code>
     */
    private $max_pokemon_storage = 0;
    /**
     * <code>int32 max_item_storage = 10;</code>
     */
    private $max_item_storage = 0;
    /**
     * <code>.POGOProtos.Data.Player.DailyBonus daily_bonus = 11;</code>
     */
    private $daily_bonus = null;
    /**
     * <code>.POGOProtos.Data.Player.EquippedBadge equipped_badge = 12;</code>
     */
    private $equipped_badge = null;
    /**
     * <code>.POGOProtos.Data.Player.ContactSettings contact_settings = 13;</code>
     */
    private $contact_settings = null;
    /**
     * <code>repeated .POGOProtos.Data.Player.Currency currencies = 14;</code>
     */
    private $currencies;
    /**
     * <code>int32 remaining_codename_claims = 15;</code>
     */
    private $remaining_codename_claims = 0;
    /**
     * <code>.POGOProtos.Data.BuddyPokemon buddy_pokemon = 16;</code>
     */
    private $buddy_pokemon = null;
    /**
     * <code>int64 battle_lockout_end_ms = 17;</code>
     */
    private $battle_lockout_end_ms = 0;
    /**
     * <code>.POGOProtos.Data.Player.PlayerAvatar secondary_player_avatar = 18;</code>
     */
    private $secondary_player_avatar = null;

    public function __construct() {
        \GPBMetadata\POGOProtos\Data\PlayerData::initOnce();
        parent::__construct();
    }

    /**
     * <code>int64 creation_timestamp_ms = 1;</code>
     */
    public function getCreationTimestampMs()
    {
        return $this->creation_timestamp_ms;
    }

    /**
     * <code>int64 creation_timestamp_ms = 1;</code>
     */
    public function setCreationTimestampMs($var)
    {
        GPBUtil::checkInt64($var);
        $this->creation_timestamp_ms = $var;
    }

    /**
     * <code>string username = 2;</code>
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * <code>string username = 2;</code>
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;
    }

    /**
     * <code>.POGOProtos.Enums.TeamColor team = 5;</code>
     */
    public function getTeam()
    {
        return $this->team;
    }

    /**
     * <code>.POGOProtos.Enums.TeamColor team = 5;</code>
     */
    public function setTeam($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Enums\TeamColor::class);
        $this->team = $var;
    }

    /**
     * <code>repeated .POGOProtos.Enums.TutorialState tutorial_state = 7 [packed = true];</code>
     */
    public function getTutorialState()
    {
        return $this->tutorial_state;
    }

    /**
     * <code>repeated .POGOProtos.Enums.TutorialState tutorial_state = 7 [packed = true];</code>
     */
    public function setTutorialState(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, POGOProtos\Enums\TutorialState::class);
        $this->tutorial_state = $var;
    }

    /**
     * <code>.POGOProtos.Data.Player.PlayerAvatar avatar = 8;</code>
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    /**
     * <code>.POGOProtos.Data.Player.PlayerAvatar avatar = 8;</code>
     */
    public function setAvatar(&$var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Data\Player\PlayerAvatar::class);
        $this->avatar = $var;
    }

    /**
     * <code>int32 max_pokemon_storage = 9;</code>
     */
    public function getMaxPokemonStorage()
    {
        return $this->max_pokemon_storage;
    }

    /**
     * <code>int32 max_pokemon_storage = 9;</code>
     */
    public function setMaxPokemonStorage($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_pokemon_storage = $var;
    }

    /**
     * <code>int32 max_item_storage = 10;</code>
     */
    public function getMaxItemStorage()
    {
        return $this->max_item_storage;
    }

    /**
     * <code>int32 max_item_storage = 10;</code>
     */
    public function setMaxItemStorage($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_item_storage = $var;
    }

    /**
     * <code>.POGOProtos.Data.Player.DailyBonus daily_bonus = 11;</code>
     */
    public function getDailyBonus()
    {
        return $this->daily_bonus;
    }

    /**
     * <code>.POGOProtos.Data.Player.DailyBonus daily_bonus = 11;</code>
     */
    public function setDailyBonus(&$var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Data\Player\DailyBonus::class);
        $this->daily_bonus = $var;
    }

    /**
     * <code>.POGOProtos.Data.Player.EquippedBadge equipped_badge = 12;</code>
     */
    public function getEquippedBadge()
    {
        return $this->equipped_badge;
    }

    /**
     * <code>.POGOProtos.Data.Player.EquippedBadge equipped_badge = 12;</code>
     */
    public function setEquippedBadge(&$var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Data\Player\EquippedBadge::class);
        $this->equipped_badge = $var;
    }

    /**
     * <code>.POGOProtos.Data.Player.ContactSettings contact_settings = 13;</code>
     */
    public function getContactSettings()
    {
        return $this->contact_settings;
    }

    /**
     * <code>.POGOProtos.Data.Player.ContactSettings contact_settings = 13;</code>
     */
    public function setContactSettings(&$var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Data\Player\ContactSettings::class);
        $this->contact_settings = $var;
    }

    /**
     * <code>repeated .POGOProtos.Data.Player.Currency currencies = 14;</code>
     */
    public function getCurrencies()
    {
        return $this->currencies;
    }

    /**
     * <code>repeated .POGOProtos.Data.Player.Currency currencies = 14;</code>
     */
    public function setCurrencies(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \POGOProtos\Data\Player\Currency::class);
        $this->currencies = $var;
    }

    /**
     * <code>int32 remaining_codename_claims = 15;</code>
     */
    public function getRemainingCodenameClaims()
    {
        return $this->remaining_codename_claims;
    }

    /**
     * <code>int32 remaining_codename_claims = 15;</code>
     */
    public function setRemainingCodenameClaims($var)
    {
        GPBUtil::checkInt32($var);
        $this->remaining_codename_claims = $var;
    }

    /**
     * <code>.POGOProtos.Data.BuddyPokemon buddy_pokemon = 16;</code>
     */
    public function getBuddyPokemon()
    {
        return $this->buddy_pokemon;
    }

    /**
     * <code>.POGOProtos.Data.BuddyPokemon buddy_pokemon = 16;</code>
     */
    public function setBuddyPokemon(&$var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Data\BuddyPokemon::class);
        $this->buddy_pokemon = $var;
    }

    /**
     * <code>int64 battle_lockout_end_ms = 17;</code>
     */
    public function getBattleLockoutEndMs()
    {
        return $this->battle_lockout_end_ms;
    }

    /**
     * <code>int64 battle_lockout_end_ms = 17;</code>
     */
    public function setBattleLockoutEndMs($var)
    {
        GPBUtil::checkInt64($var);
        $this->battle_lockout_end_ms = $var;
    }

    /**
     * <code>.POGOProtos.Data.Player.PlayerAvatar secondary_player_avatar = 18;</code>
     */
    public function getSecondaryPlayerAvatar()
    {
        return $this->secondary_player_avatar;
    }

    /**
     * <code>.POGOProtos.Data.Player.PlayerAvatar secondary_player_avatar = 18;</code>
     */
    public function setSecondaryPlayerAvatar(&$var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Data\Player\PlayerAvatar::class);
        $this->secondary_player_avatar = $var;
    }

}

