<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/PokemonDisplay.proto

/**
 * Protobuf enum <code>POGOProtos.Data.PokemonDisplay.Costume</code>
 */
namespace POGOProtos\Data;

class PokemonDisplay_Costume
{
    /**
     * <code>UNSET = 0;</code>
     */
    const UNSET_VALUE = 0;
    /**
     * <code>HOLIDAY_2016 = 1;</code>
     */
    const HOLIDAY_2016 = 1;
}

