<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Inventory/Candy.proto

namespace GPBMetadata\POGOProtos\Inventory;

class Candy
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Enums\PokemonFamilyId::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab6010a20504f474f50726f746f732f496e76656e746f72792f43616e64" .
            "792e70726f746f1214504f474f50726f746f732e496e76656e746f72791a" .
            "26504f474f50726f746f732f456e756d732f506f6b656d6f6e46616d696c" .
            "7949642e70726f746f224c0a0543616e647912340a0966616d696c795f69" .
            "6418012001280e32212e504f474f50726f746f732e456e756d732e506f6b" .
            "656d6f6e46616d696c794964120d0a0563616e6479180220012805620670" .
            "726f746f33"
        ));

        static::$is_initialized = true;
    }
}

