<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Inventory/InventoryUpgrades.proto

namespace GPBMetadata\POGOProtos\Inventory;

class InventoryUpgrades
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Inventory\InventoryUpgrade::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad2010a2c504f474f50726f746f732f496e76656e746f72792f496e7665" .
            "6e746f727955706772616465732e70726f746f1214504f474f50726f746f" .
            "732e496e76656e746f72791a2b504f474f50726f746f732f496e76656e74" .
            "6f72792f496e76656e746f7279557067726164652e70726f746f22570a11" .
            "496e76656e746f7279557067726164657312420a12696e76656e746f7279" .
            "5f757067726164657318012003280b32262e504f474f50726f746f732e49" .
            "6e76656e746f72792e496e76656e746f727955706772616465620670726f" .
            "746f33"
        ));

        static::$is_initialized = true;
    }
}

