<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Inventory/InventoryUpgrade.proto

namespace GPBMetadata\POGOProtos\Inventory;

class InventoryUpgrade
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Inventory\Item\ItemId::initOnce();
        \GPBMetadata\POGOProtos\Inventory\InventoryUpgradeType::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0acb020a2b504f474f50726f746f732f496e76656e746f72792f496e7665" .
            "6e746f7279557067726164652e70726f746f1214504f474f50726f746f73" .
            "2e496e76656e746f72791a26504f474f50726f746f732f496e76656e746f" .
            "72792f4974656d2f4974656d49642e70726f746f1a2f504f474f50726f74" .
            "6f732f496e76656e746f72792f496e76656e746f72795570677261646554" .
            "7970652e70726f746f22a4010a10496e76656e746f727955706772616465" .
            "12320a076974656d5f696418012001280e32212e504f474f50726f746f73" .
            "2e496e76656e746f72792e4974656d2e4974656d496412400a0c75706772" .
            "6164655f7479706518022001280e322a2e504f474f50726f746f732e496e" .
            "76656e746f72792e496e76656e746f72795570677261646554797065121a" .
            "0a126164646974696f6e616c5f73746f7261676518032001280562067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

